// AUTO-GENERATED by tools/anima/gen_knowledge_manifest.mjs — DO NOT EDIT.
// SHA-256 of the shipped ANIMA knowledge files = the device-side root of trust (see docs/anima-knowledge-graph.md).
#pragma once

#define VKL_FACETS_IT_SHA256 "a00d66fbc96bafadda334fa5284241d67d40af0b5320f711fd408227eeb45f8f"
#define VKL_FACETS_EN_SHA256 "1d8f79726fb620276ca4b2de06ddc12f9419590d8dc1760589cb66a55d1af359"
#define VKL_MIND_IT_SHA256 "3fe58d293033dd2784033f45ec3c50d95a7bea81a0cf4736baa4d3920ece6f92"
#define VKL_MIND_EN_SHA256 "3314811bc6eaea78977a77139d407ffb02a982c5400cdb527a94b3722ae07e55"
