#!/usr/bin/env python3
"""ANIMA bulk dictionary importer — downloads WHOLE bilingual dictionaries (FreeDict ita-eng + eng-ita,
CC-BY-SA / GPL) in one shot and emits an IT<->EN seed that gen_dicts.py normalizes + sorts into the device
TSVs. No per-word API calls. The firmware then binary-searches the sorted file on SD (zero resident RAM),
so the FULL ~80k-headword bilingual dictionary lives on the microcontroller and answers offline.

Run:  python tools/anima/build_dict.py      (network needed once; cached under tools/anima/.cache/freedict)
Then: python tools/anima/gen_dicts.py       (rebuilds dict-it-en.tsv / dict-en-it.tsv from all seeds)
"""
import os, sys, io, re, lzma, tarfile, urllib.request, xml.etree.ElementTree as ET

HERE  = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(HERE, ".cache", "freedict"); os.makedirs(CACHE, exist_ok=True)
# TWO directional seeds (both in IT<TAB>EN shape). gen_dicts builds dict-it-en ONLY from the IT->EN seed
# (ita-eng forward) and dict-en-it ONLY from the EN->IT seed (eng-ita forward) — so each direction keeps
# FreeDict's native sense order (primary first) instead of being polluted by the OTHER dict's reverse
# aggregation, which alphabetised rare senses to the front (drink->"abbeverare" instead of "bere").
OUT_ITEN = os.path.join(HERE, "dict", "seed.freedict.it-en.tsv")
OUT_ENIT = os.path.join(HERE, "dict", "seed.freedict.en-it.tsv")
UA    = "NucleoOS-ANIMA/1.0 (offline pocket dictionary; grounded, no-hallucination)"
SRCS  = {  # name -> (url, orth_lang)  orth_lang = language of the headword (<orth>)
  "ita-eng": ("https://download.freedict.org/dictionaries/ita-eng/2025.11.23/freedict-ita-eng-2025.11.23.src.tar.xz", "it"),
  "eng-ita": ("https://download.freedict.org/dictionaries/eng-ita/2025.11.23/freedict-eng-ita-2025.11.23.src.tar.xz", "en"),
}
MAX_TR   = 4     # keep at most N translations per headword (the rest are rarer senses / noise)
MAX_VLEN = 90    # cap a value cell so dict lines stay small (fast SD lines)
LN = "{http://www.tei-c.org/ns/1.0}"   # TEI default namespace

def fetch(name, url):
    cf = os.path.join(CACHE, name + ".tar.xz")
    if not os.path.exists(cf):
        req = urllib.request.Request(url, headers={"User-Agent": UA})
        with urllib.request.urlopen(req, timeout=60) as r, open(cf, "wb") as o: o.write(r.read())
    return cf

def tei_bytes(tarxz):
    with lzma.open(tarxz) as xz, tarfile.open(fileobj=io.BytesIO(xz.read())) as tf:
        m = next((x for x in tf.getmembers() if x.name.endswith(".tei")), None)
        if not m: raise RuntimeError("no .tei in " + tarxz)
        return tf.extractfile(m).read()

# Accept ONLY clean Latin terms: drops non-Latin scripts (Cyrillic "подобно", Arabic, CJK that pollute some
# FreeDict cells) and lone-letter junk ("tre -> three, E"). A confident garbage translation = a hallucination.
LATIN = re.compile(r"^[A-Za-zÀ-ÖØ-öø-ÿ0-9][A-Za-zÀ-ÖØ-öø-ÿ0-9 '.\-/()]*$")
_TYPO = {"’": "'", "‘": "'", "“": '"', "”": '"', "–": "-",
         "—": "-", " ": " ", "…": "...", "ʼ": "'"}
def norm_term(t):
    t = (t or "").strip()
    for k, v in _TYPO.items(): t = t.replace(k, v)   # typographic -> ASCII (device renders only ASCII+Latin1)
    return t
def ok_term(t):
    return len(t) >= 2 and bool(LATIN.match(t))

def parse(tei, orth_lang):
    """Return list of (it_terms[list], en_terms[list]) pairs from one TEI body."""
    root = ET.fromstring(tei)
    out = []
    for entry in root.iter(LN + "entry"):
        orth = entry.find(f"./{LN}form/{LN}orth")
        if orth is None or not (orth.text or "").strip(): continue
        head = norm_term(orth.text)
        if not ok_term(head): continue
        trans = []
        for cit in entry.iter(LN + "cit"):
            if cit.get("type") not in (None, "trans"): continue
            for q in cit.iter(LN + "quote"):
                t = norm_term(q.text)
                if t and ok_term(t) and t not in trans: trans.append(t)
        trans = trans[:MAX_TR]
        if not trans: continue
        if orth_lang == "it": out.append(([head], trans))      # IT head -> EN trans
        else:                 out.append((trans, [head]))       # EN head -> IT trans
    return out

def cell(terms):
    s = "; ".join(terms)
    return s[:MAX_VLEN].rsplit(";", 1)[0].strip() if len(s) > MAX_VLEN else s

def write_seed(path, pairs):
    seen, rows = set(), []
    for it_terms, en_terms in pairs:                  # each pair already in (IT, EN) shape, forward order
        it, en = cell(it_terms), cell(en_terms)
        if not it or not en: continue
        k = (it.lower(), en.lower())
        if k in seen: continue
        seen.add(k); rows.append(it + "\t" + en)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("# AUTO-GENERATED by build_dict.py from FreeDict (CC-BY-SA/GPL). Do not hand-edit.\n")
        f.write("\n".join(rows) + "\n")
    return len(rows)

def main():
    # ita-eng -> IT->EN seed (IT head, EN trans);  eng-ita -> EN->IT seed (IT trans, EN head). Both IT<TAB>EN.
    iten = parse(tei_bytes(fetch("ita-eng", SRCS["ita-eng"][0])), "it")
    enit = parse(tei_bytes(fetch("eng-ita", SRCS["eng-ita"][0])), "en")
    print(f"[dict] ita-eng: {len(iten)} entries   eng-ita: {len(enit)} entries")
    n1 = write_seed(OUT_ITEN, iten)
    n2 = write_seed(OUT_ENIT, enit)
    print(f"[dict] wrote {n1} rows -> {OUT_ITEN}")
    print(f"[dict] wrote {n2} rows -> {OUT_ENIT}")
    print(f"[dict] next: python tools/anima/gen_dicts.py   (each direction from its OWN forward seed)")

if __name__ == "__main__":
    main()
