#!/usr/bin/env python3
"""Grow ANIMA's deductive brain: extract source-anchored, BILINGUAL (subject, rel, value) triples into
mind.it.jsonl + mind.en.jsonl (and the sd-sim/host fixtures), so the on-device permutation-KGE + the
neuro-symbolic combinator can DEDUCE/COMPOSE over hundreds of facts instead of a demo 23.

Two source layers, both verifiable (0 hallucination — ANIMA's contract):
  GEOGRAPHY  from tools/anima/refdata/world.json — the maintainable bilingual gazetteer (165 countries:
             continent + capital + demonyms, IT/EN). Generated by build_refdata.mjs: a curated CORE of
             ~49 load-bearing countries (authoritative) + Groq breadth, with continents measured 100%
             reliable and capitals card-verified. -> capital (city->country) + located_in (city->country,
             country->continent) for every country.
  PEOPLE     from people.jsonl — born from a STRUCTURED birth parenthesis only ("(1769-1821)"/"(born 1958)";
             never reign/death prose), + four canonical seeds whose bios omit it. country via the bio's EN
             demonym mapped through the gazetteer. (Groq is NOT used for birth years: measured 49% accurate
             on non-famous people — born stays source-anchored; the online Wikidata tier fills the rest.)

   python tools/anima/extract_triples.py            # dry-run: counts + self-checks + samples
   python tools/anima/extract_triples.py --apply    # write all fixtures
"""
import os, sys, re, json, argparse, unicodedata

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
KDIR = os.path.join(ROOT, "tools", "anima", "knowledge")
WORLD = os.path.join(ROOT, "tools", "anima", "refdata", "world.json")
TAX = os.path.join(ROOT, "tools", "anima", "refdata", "taxonomy.json")
FIXTURES = [
    os.path.join(ROOT, "deploy", "sd", "data", "anima", "learned"),
    os.path.join(ROOT, "tools", "sd-sim", "data", "anima", "learned"),
    os.path.join(ROOT, "tools", "anima-host", "sd", "data", "anima", "learned"),
]

# demonym forms that appear in bios but aren't the gazetteer's canonical demonym_en
DEMONYM_ALIAS = {
    "English": "Regno Unito", "Scottish": "Regno Unito", "Welsh": "Regno Unito",
    "Soviet": "Russia", "Argentinian": "Argentina", "Anglo": "Regno Unito",
}
SEED_PEOPLE = [
    ("albert-einstein", "Albert Einstein", "14 marzo 1879", "14 March 1879", "Germania"),
    ("dante-alighieri", "Dante Alighieri", "1265", "1265", "Italia"),
    ("cristoforo-colombo", "Cristoforo Colombo", "1451", "1451", "Italia"),
    ("isaac-newton", "Isaac Newton", "4 gennaio 1643", "4 January 1643", "Regno Unito"),
]
# Occupation/gender for the seeds (their bios live here, not in people.jsonl): slug, occ_it, occ_en, gender.
SEED_FACETS = [
    ("albert-einstein", "scienziato", "scientist", "M"),
    ("dante-alighieri", "scrittore", "writer", "M"),
    ("cristoforo-colombo", "esploratore", "explorer", "M"),
    ("isaac-newton", "scienziato", "scientist", "M"),
]

BIRTH = re.compile(
    r"\((?:born\s+|b\.\s*|n\.\s*|nato\s+(?:nel\s+)?)?(1[0-9]{3}|20[0-2][0-9])\s*[–—\-]\s*(?:1[0-9]{3}|20[0-2][0-9])?\)"
    r"|\(\s*(?:born|b\.)\s*(1[0-9]{3}|20[0-2][0-9])\s*\)")
# died: only from a CLOSED life-span parenthesis "(1769-1821)" / "(1958–2016)" — never reign/prose.
# A "(born 1958)" or open-ended "(1958–)" yields no death year (the person may be living).
DIED = re.compile(r"\((?:1[0-9]{3}|20[0-2][0-9])\s*[–—\-]\s*(1[0-9]{3}|20[0-2][0-9])\)")
DEM_BORN = re.compile(r"\b(?:was|is|were|are)\s+(?:an?|the)\s+[A-Z][a-z]+-born\s+([A-Z][a-z]+)")
DEM_TWO = re.compile(r"\b(?:was|is|were|are)\s+(?:an?|the)\s+(South African|South Korean|New Zealander)\b")
DEM_ONE = re.compile(r"\b(?:was|is|were|are)\s+(?:an?|the)\s+([A-Z][a-z]+)")
NAME = re.compile(r"^(.{2,40}?)\s+(?:è|e|was|is|were|are)\b")


def slug(s):
    s = unicodedata.normalize("NFD", s.lower())
    s = "".join(c for c in s if unicodedata.category(c) != "Mn")
    return "-".join("".join(c if c.isalnum() else " " for c in s).split())


def load_world():
    w = json.load(open(WORLD, encoding="utf-8"))
    country = {}   # country_it -> (country_en, continent_it, continent_en, capital_it, capital_en)
    demonym = {}   # demonym_en -> country_it
    for it, r in w.items():
        country[it] = (r["name_en"], r["continent_it"], r["continent_en"], r.get("capital_it", ""), r.get("capital_en", ""))
        for d in (r.get("demonym_en", ""),):
            if d:
                demonym.setdefault(d, it)
                demonym.setdefault(d[:1].upper() + d[1:], it)
    demonym.update(DEMONYM_ALIAS)
    return country, demonym


def load_taxonomy():
    t = json.load(open(TAX, encoding="utf-8"))
    # form (lowercase surface word/phrase) -> bucket object, per language. Longer forms first so a
    # multi-word phrase ("primo ministro") is preferred over a contained single word.
    occ_it, occ_en = {}, {}
    for o in t["occupations"]:
        for f in o.get("forms_it", []):
            occ_it[f.lower()] = o
        for f in o.get("forms_en", []):
            occ_en[f.lower()] = o
    return t, occ_it, occ_en


# match a controlled occupation form as a whole word/phrase; return the bucket whose form appears
# EARLIEST in the bio (the primary occupation, e.g. "cantautore" in "cantautore e chitarrista").
def find_occ(text, forms):
    tl = " " + re.sub(r"[^0-9a-zàèéìòóù' ]+", " ", (text or "").lower()) + " "
    tl = re.sub(r"\s+", " ", tl)
    best, bestpos = None, 10 ** 9
    for form, o in forms.items():
        i = tl.find(" " + form + " ")
        if 0 <= i < bestpos:
            bestpos, best = i, o
    return best


# gender from high-confidence morphology only (else abstain): IT past participle "è stato/è stata",
# then EN pronoun majority, then a gendered occupation noun. Bios are one sentence → high precision.
def find_gender(it_t, en_t):
    m = re.search(r"\b[eè]\s+stat([oa])\b", (it_t or "").lower())
    if m:
        return "M" if m.group(1) == "o" else "F"
    m = re.search(r"\bfu\s+un(a)?\b", (it_t or "").lower())
    if m:
        return "F" if m.group(1) else "M"
    t = " " + (en_t or "").lower() + " "
    he = len(re.findall(r"\b(?:he|his|him)\b", t))
    she = len(re.findall(r"\b(?:she|her|hers)\b", t))
    if he or she:
        return "M" if he > she else ("F" if she > he else None)
    if re.search(r"\b(?:attrice|actress)\b", ((it_t or "") + " " + (en_t or "")).lower()):
        return "F"
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    args = ap.parse_args()
    COUNTRY, DEMONYM = load_world()
    TAXO, OCC_IT, OCC_EN = load_taxonomy()
    GEN = TAXO["gender"]   # {"M": {"it":"uomo","en":"man"}, "F": {...}}

    rows = {"it": [], "en": []}            # mind.*.jsonl  (relational chains -> device KGE)
    seen = {"it": set(), "en": set()}
    frows = {"it": [], "en": []}           # facets.*.jsonl (categorical -> inverted index + type-gate)
    fseen = {"it": set(), "en": set()}

    def add(lang, subject, rel, value, label):
        ks = (slug(subject), rel, slug(value))
        if not ks[0] or not ks[2] or ks in seen[lang]:
            return
        seen[lang].add(ks)
        rows[lang].append({"subject": ks[0], "rel": rel, "value": value, "label": label})

    def addf(lang, subject, rel, value, label):   # categorical facet (separate store)
        ks = (slug(subject), rel, slug(value))
        if not ks[0] or not ks[2] or ks in fseen[lang]:
            return
        fseen[lang].add(ks)
        frows[lang].append({"subject": ks[0], "rel": rel, "value": value, "label": label})

    def add_person_facets(pslug, label, occ_it, occ_en, gender):
        addf("it", pslug, "isa", "persona", label); addf("en", pslug, "isa", "person", label)
        if occ_it and occ_en:
            addf("it", pslug, "occupation", occ_it, label)
            addf("en", pslug, "occupation", occ_en, label)
        if gender in GEN:
            addf("it", pslug, "gender", GEN[gender]["it"], label)
            addf("en", pslug, "gender", GEN[gender]["en"], label)

    # ---- GEO: capital (city->country) + located_in (city->country, country->continent) ----
    for country_it, (country_en, cont_it, cont_en, cap_it, cap_en) in COUNTRY.items():
        if cap_it and cap_en:
            add("it", cap_it, "capital", country_it, cap_it);  add("en", cap_en, "capital", country_en, cap_en)
            add("it", cap_it, "located_in", country_it, cap_it); add("en", cap_en, "located_in", country_en, cap_en)
            addf("it", cap_it, "isa", "luogo", cap_it); addf("en", cap_en, "isa", "place", cap_en)
        add("it", country_it, "located_in", cont_it, country_it)
        add("en", country_en, "located_in", cont_en, country_en)
        addf("it", country_it, "isa", "luogo", country_it); addf("en", country_en, "isa", "place", country_en)
        addf("it", cont_it, "isa", "luogo", cont_it); addf("en", cont_en, "isa", "place", cont_en)

    # ---- canonical seed people ----
    for pslug, label, byr_it, byr_en, country_it in SEED_PEOPLE:
        add("it", pslug, "born", byr_it, label);  add("en", pslug, "born", byr_en, label)
        add("it", pslug, "country", country_it, label)
        add("en", pslug, "country", COUNTRY[country_it][0], label)
    for pslug, occ_it, occ_en, gender in SEED_FACETS:
        add_person_facets(pslug, pslug.replace("-", " ").title(), occ_it, occ_en, gender)

    # ---- PEOPLE: structured born + demonym country ----
    seeded = {p[0] for p in SEED_PEOPLE}
    n_born = n_ctry = n_died = n_occ = n_gen = 0
    for line in open(os.path.join(KDIR, "people.jsonl"), encoding="utf-8"):
        s = line.strip()
        if not s or s.startswith("//"):
            continue
        c = json.loads(s)
        if not c.get("id", "").startswith("person.") or c["id"][len("person."):] in seeded:
            continue
        pslug = c["id"][len("person."):]
        r = c.get("reply", {}); it_t, en_t = r.get("it", "") or "", r.get("en", "") or ""
        nm = NAME.match(it_t) or NAME.match(en_t)
        label = nm.group(1).strip() if nm else pslug.replace("-", " ").title()
        bm = BIRTH.search(it_t) or BIRTH.search(en_t)
        if bm:
            yr = bm.group(1) or bm.group(2)
            add("it", pslug, "born", yr, label); add("en", pslug, "born", yr, label); n_born += 1
        dym = DIED.search(it_t) or DIED.search(en_t)   # closed life-span only -> death year
        if dym:
            add("it", pslug, "died", dym.group(1), label); add("en", pslug, "died", dym.group(1), label); n_died += 1
        dm = DEM_BORN.search(en_t) or DEM_TWO.search(en_t) or DEM_ONE.search(en_t)
        country_it = DEMONYM.get(dm.group(1)) if dm else None
        if country_it and country_it in COUNTRY:
            add("it", pslug, "country", country_it, label)
            add("en", pslug, "country", COUNTRY[country_it][0], label); n_ctry += 1
        # ---- CATEGORICAL FACETS (separate store): occupation bucket + gender + isa person ----
        occ = find_occ(it_t, OCC_IT) or find_occ(en_t, OCC_EN)   # one bucket -> bilingual by construction
        gender = find_gender(it_t, en_t)
        add_person_facets(pslug, label, occ["it"] if occ else None, occ["en"] if occ else None, gender)
        if occ:
            n_occ += 1
        if gender in GEN:
            n_gen += 1

    # ============ SELF-CHECKS (the data regression gate) ============
    errors = []
    known_cities = {slug(v[3]) for v in COUNTRY.values() if v[3]} | {slug(v[4]) for v in COUNTRY.values() if v[4]}
    known_countries = {slug(k) for k in COUNTRY} | {slug(v[0]) for v in COUNTRY.values()}
    for lang in ("it", "en"):
        located_heads = {t["subject"] for t in rows[lang] if t["rel"] == "located_in"}
        for t in rows[lang]:
            if t["rel"] == "capital" and slug(t["value"]) in known_cities and slug(t["value"]) not in known_countries:
                errors.append(f"[{lang}] capital value is a CITY (inverted): {t}")
            if t["rel"] == "country" and slug(t["value"]) not in located_heads:
                errors.append(f"[{lang}] country '{t['value']}' has no located_in head (continent chain broken): {t['subject']}")
    if len(rows["it"]) != len(rows["en"]):
        errors.append(f"parity: it={len(rows['it'])} != en={len(rows['en'])}")
    if {t["subject"] for t in rows["it"] if t["rel"] in ("born", "country", "died")} != \
       {t["subject"] for t in rows["en"] if t["rel"] in ("born", "country", "died")}:
        errors.append("parity: person slug-set differs between it/en")

    # ---- facet self-checks: it/en parity + must-hold spot-checks (the typed-data regression) ----
    # PERSON facets carry language-INDEPENDENT slugs (e.g. albert-einstein) -> sets must match.
    # GEO isa carries localized slugs (roma vs rome); counts may differ from benign name collisions.
    def psubs(lang, rel, val_slugs=None):
        return {t["subject"] for t in frows[lang]
                if t["rel"] == rel and (val_slugs is None or slug(t["value"]) in val_slugs)}
    if psubs("it", "occupation") != psubs("en", "occupation"):
        errors.append("facets parity: occupation subject-set differs it/en")
    if psubs("it", "gender") != psubs("en", "gender"):
        errors.append("facets parity: gender subject-set differs it/en")
    if psubs("it", "isa", {"persona"}) != psubs("en", "isa", {"person"}):
        errors.append("facets parity: isa-person subject-set differs it/en")
    fit = {(t["subject"], t["rel"]): slug(t["value"]) for t in frows["it"]}
    mit = {(t["subject"], t["rel"]): slug(t["value"]) for t in rows["it"]}
    for subj, rel, want, table in [
        ("michael-jackson", "occupation", "musicista", fit),
        ("michael-jackson", "gender", "uomo", fit),
        ("michael-jackson", "isa", "persona", fit),
        ("albert-einstein", "occupation", "scienziato", fit),
        ("albert-einstein", "isa", "persona", fit),
        ("prince-musician", "died", "2016", mit),
        ("roma", "isa", "luogo", fit),
    ]:
        got = table.get((subj, rel))
        if got != want:
            errors.append(f"spot-check: ({subj}, {rel}) = {got!r}, expected {want!r}")

    from collections import Counter
    for lang in ("it", "en"):
        byrel = Counter(t["rel"] for t in rows[lang])
        print(f"[triples] mind.{lang}.jsonl: {len(rows[lang])}  " +
              "  ".join(f"{r}={byrel[r]}" for r in ("capital", "located_in", "born", "died", "country")))
    for lang in ("it", "en"):
        byrel = Counter(t["rel"] for t in frows[lang])
        print(f"[facets]  facets.{lang}.jsonl: {len(frows[lang])}  " +
              "  ".join(f"{r}={byrel[r]}" for r in ("isa", "occupation", "gender")))
    print(f"  gazetteer: {len(COUNTRY)} countries  |  people: born={n_born + len(SEED_PEOPLE)}  "
          f"died={n_died}  country={n_ctry + len(SEED_PEOPLE)}  occupation={n_occ + len(SEED_FACETS)}  gender={n_gen + len(SEED_FACETS)}")
    if errors:
        print(f"\n[SELF-CHECK] {len(errors)} FAILURES:")
        for e in errors[:20]:
            print("   -", e)
        sys.exit(1)
    print("[SELF-CHECK] capital-direction, continent reachability, died/facet parity, spot-checks: ALL PASS")

    if not args.apply:
        print("\n[dry-run] nothing written. Re-run with --apply.")
        return
    for lang in ("it", "en"):
        mind_body = "\n".join(json.dumps(t, ensure_ascii=False) for t in rows[lang]) + "\n"
        fac_body = "\n".join(json.dumps(t, ensure_ascii=False) for t in frows[lang]) + "\n"
        for d in FIXTURES:
            os.makedirs(d, exist_ok=True)
            with open(os.path.join(d, f"mind.{lang}.jsonl"), "w", encoding="utf-8", newline="\n") as f:
                f.write(mind_body)
            with open(os.path.join(d, f"facets.{lang}.jsonl"), "w", encoding="utf-8", newline="\n") as f:
                f.write(fac_body)
    print(f"\n[apply] wrote mind.{{it,en}} ({len(rows['it'])}) + facets.{{it,en}} ({len(frows['it'])}) to {len(FIXTURES)} fixtures.")


if __name__ == "__main__":
    main()
