#!/usr/bin/env node
// Generate firmware/components/nucleo_anima/nucleo_knowledge_manifest.h — the OFF-SD root of trust the
// device embeds (in its read-only firmware .bin, NOT on the removable SD, and NOT in irreversible eFuse).
// It pins the SHA-256 of each knowledge file the device reads, so at runtime the device can verify the SD
// copy is the genuine shipped knowledge (tamper -> the tier abstains). Reversible: a new release just
// re-embeds fresh hashes. Re-run after the knowledge changes (extract_triples / enrich):
//   node tools/anima/gen_knowledge_manifest.mjs
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const REPO = join(here, '..', '..');
const SRC = join(REPO, 'deploy', 'sd', 'data', 'anima', 'learned');   // the canonical shipped knowledge
const OUT = join(REPO, 'firmware', 'components', 'nucleo_anima', 'nucleo_knowledge_manifest.h');

// file -> C macro. The device currently READS facets (typed tier) + mind (KGE); evo/ledger are host-side
// (closure/provenance) for now, hashed too so a future device closure tier can verify them.
const FILES = [
  ['facets.it.jsonl', 'VKL_FACETS_IT_SHA256'], ['facets.en.jsonl', 'VKL_FACETS_EN_SHA256'],
  ['mind.it.jsonl', 'VKL_MIND_IT_SHA256'], ['mind.en.jsonl', 'VKL_MIND_EN_SHA256'],
];
const sha = (p) => createHash('sha256').update(readFileSync(p)).digest('hex');

const lines = [
  '// AUTO-GENERATED by tools/anima/gen_knowledge_manifest.mjs — DO NOT EDIT.',
  '// SHA-256 of the shipped ANIMA knowledge files = the device-side root of trust (see docs/anima-knowledge-graph.md).',
  '#pragma once', '',
];
for (const [f, macro] of FILES) {
  const p = join(SRC, f);
  if (!existsSync(p)) { console.error('[manifest] MISSING', f); process.exit(1); }
  lines.push(`#define ${macro} "${sha(p)}"`);
}
lines.push('');
writeFileSync(OUT, lines.join('\n'), 'utf8');
console.log('[manifest] wrote', OUT);
for (const [f, macro] of FILES) console.log(`  ${macro} = ${sha(join(SRC, f)).slice(0, 16)}…  (${f})`);
