#!/usr/bin/env node
// ACTION / CONVERSATION STRESS — "ask ANIMA to DO things" at scale, in natural language.
// Phrase DIVERSITY is generated by a LOCAL model (Ollama) so it costs no API tokens; the generated
// phrases are cached to action-phrases.jsonl and replayed through the REAL pipeline (anima.exe).
// For each phrase we assert the agent loop routes to the EXPECTED tool intent. Misroutes are printed
// so an NLU gap (fix it) is separated from a bad generation (drop it).
//
//   node tools/anima-host/action-stress.mjs --gen     # (re)generate phrases via Ollama, then run
//   node tools/anima-host/action-stress.mjs           # replay the cached phrases (no Ollama)
//   node tools/anima-host/action-stress.mjs --show     # list every phrase + routed intent
import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const exe = join(here, 'build', 'anima.exe');
const cache = join(here, 'action-phrases.jsonl');
const MODEL = process.env.OLLAMA_MODEL || 'llama3.1:8b';
if (!existsSync(exe)) { console.error('anima.exe missing — run `npm run anima:build`.'); process.exit(2); }

// category -> { accept: Set(intents), seeds: [...canonical floor...], prompt: ollama instruction }
const CATS = {
  create_file: {
    accept: ['create_file'],
    seeds: ['crea una nota con la lista della spesa', 'scrivi un file diario.txt con oggi è andata bene',
            'crea un appunto con comprare il pane', 'make a note saying call mom', 'create a file todo.txt with buy milk'],
    prompt: 'short commands a user says to CREATE a text note or file with some content (e.g. a shopping list, a reminder text). Mix Italian and English.' },
  set_volume: {
    accept: ['set_volume'],
    seeds: ['imposta il volume a 40', 'alza il volume', 'abbassa il volume', 'metti il volume al 70 percento', 'turn the volume up'],
    prompt: 'short commands a user says to CHANGE THE VOLUME (raise, lower, or set to a number). Mix Italian and English.' },
  set_brightness: {
    accept: ['set_brightness'],
    seeds: ['imposta la luminosita a 30', 'abbassa la luminosita', 'alza la luminosita dello schermo', 'set the brightness to 50'],
    prompt: 'short commands a user says to CHANGE SCREEN BRIGHTNESS. Mix Italian and English.' },
  add_event: {
    accept: ['add_event'],
    seeds: ['ricordami di chiamare il dottore domani alle 9', 'aggiungi un evento riunione dopodomani alle 15',
            'promemoria comprare il latte', 'remind me to send the email tomorrow at 10'],
    prompt: 'short commands a user says to SET A REMINDER or calendar event (with or without a time). Mix Italian and English.' },
  open_app: {
    accept: ['open_app'],
    seeds: ['apri la calcolatrice', 'apri il calendario', 'metti la musica', 'avvia il browser', 'open the settings'],
    prompt: 'short commands a user says to OPEN/LAUNCH an app among: calcolatrice, calendario, musica, browser, impostazioni, radio, blocco note, file. Mix Italian and English.' },
};

function ollamaLines(prompt, n) {
  const full = `Generate exactly ${n} ${prompt}\nOutput ONLY the phrases, one per line, no numbering, no quotes, no extra commentary.`;
  const r = spawnSync('ollama', ['run', MODEL, full], { encoding: 'utf8', timeout: 120000, maxBuffer: 8 * 1024 * 1024 });
  const out = (r.stdout || '');
  return out.split(/\r?\n/).map(s => s.replace(/^[\s\-\d.)"*]+/, '').trim())
    .filter(s => s.length >= 6 && s.length <= 90 && /[a-zA-Z]/.test(s) && !/^(here|ecco|sure|certo|output)/i.test(s));
}

let items = [];
if (process.argv.includes('--gen')) {
  for (const [cat, c] of Object.entries(CATS)) {
    process.stdout.write(`  generating ${cat} via ${MODEL} ...\n`);
    let gen = [];
    try { gen = ollamaLines(c.prompt, 14); } catch { gen = []; }
    const phrases = [...new Set([...c.seeds, ...gen])];
    for (const q of phrases) items.push({ q, cat });
  }
  writeFileSync(cache, items.map(i => JSON.stringify(i)).join('\n') + '\n');
  console.log(`  cached ${items.length} phrases -> ${cache}`);
} else if (existsSync(cache)) {
  items = readFileSync(cache, 'utf8').split(/\r?\n/).filter(Boolean).map(l => JSON.parse(l));
} else {
  for (const [cat, c] of Object.entries(CATS)) for (const q of c.seeds) items.push({ q, cat });
}

// run through the pipeline
const lines = [];
for (const it of items) { lines.push('/reset'); lines.push(it.q); }
const r = spawnSync(exe, [], { input: Buffer.from(lines.join('\n') + '\n', 'utf8'), maxBuffer: 64 * 1024 * 1024 });
const blocks = r.stdout.toString('utf8').split(/^Q: /m).slice(1);
const intentOf = b => (b.match(/intent=(\S*)/) || [])[1] || '';

const show = process.argv.includes('--show');
const by = {}; const miss = [];
for (let i = 0; i < items.length; i++) {
  const it = items[i], intent = intentOf(blocks[i] || '');
  const ok = CATS[it.cat].accept.includes(intent);
  by[it.cat] = by[it.cat] || { n: 0, ok: 0 };
  by[it.cat].n++; if (ok) by[it.cat].ok++;
  if (!ok) miss.push([it.cat, it.q, intent || '(none)']);
  if (show) console.log(`${ok ? '  ok  ' : 'MISS  '} [${it.cat}] "${it.q}" -> ${intent || '(none)'}`);
}

let tot = 0, tok = 0;
console.log(`\n[action-stress] ${items.length} NL action requests over the real pipeline`);
for (const [cat, s] of Object.entries(by)) { tot += s.n; tok += s.ok; console.log(`  ${cat.padEnd(16)} ${s.ok}/${s.n} routed correctly`); }
console.log(`  TOTAL: ${tok}/${tot} (${(100 * tok / tot).toFixed(1)}%)`);
if (miss.length) { console.log('\nMISROUTES:'); for (const m of miss.slice(0, 40)) console.log(`  ✗ [${m[0]}] "${m[1]}" -> ${m[2]}`); }
