// AUTO-GENERATED by tools/anima/gen_knowledge_manifest.mjs — DO NOT EDIT.
// SHA-256 of the shipped ANIMA knowledge files = the device-side root of trust (see docs/anima-knowledge-graph.md).
#pragma once

#define VKL_FACETS_IT_SHA256 "46d07f41695a0c851c7d520a03020bbe7ee0912db7b3f1e9f15072bb432c3e6e"
#define VKL_FACETS_EN_SHA256 "1d8f79726fb620276ca4b2de06ddc12f9419590d8dc1760589cb66a55d1af359"
#define VKL_MIND_IT_SHA256 "b41fbcada29e2332519f7542825cde567b98bdfaa05ed0acd1f486107324576b"
#define VKL_MIND_EN_SHA256 "3314811bc6eaea78977a77139d407ffb02a982c5400cdb527a94b3722ae07e55"
