#!/usr/bin/env python3
"""
ANIMA Test Lab — an intelligent, scalable, modular HEALTH MONITOR for ANIMA (not just a test runner).

It reads the single central catalog tools/test-registry.json (generated by tools/gen-test-registry.mjs)
and gives three views:
  • Panoramica  — ANIMA's health at a glance: hallucinations (must be 0), NL cases covered, routing drift,
                  green/total, per-category health, and ▲▼ trend vs the previous run.
  • Test        — the one-button cockpit: ▶ Esegui tutti (every test that makes sense offline, no web
                  models), or only-NL / a category / the selection / the failed ones.
  • Andamento   — sparklines of the health metrics across runs (is ANIMA getting better or worse?).

MODULAR + SCALABLE by design: a new test added as a *.test.mjs or wired into gate.mjs appears here on the
next `npm run test:registry` with zero edits; if it declares a metric (k=cases/halluc/diffs) in the
generator's METRICS map, it lifts the dashboard automatically. Runs are appended to history.jsonl for trends.

    python tools/test-lab/test_lab.py        (or: npm run test:lab)

Standard library only (tkinter).
"""
import json
import os
import queue
import re
import subprocess
import sys
import threading
import time
import tkinter as tk
from datetime import datetime
from tkinter import ttk, font as tkfont

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
REGISTRY = os.path.join(REPO, "tools", "test-registry.json")
HISTORY = os.path.join(HERE, "history.jsonl")
REPORTS = os.path.join(HERE, "reports")   # report per-corsa (JSON+MD), versionati + latest + index.jsonl
KEEP_REPORTS = 40                          # quanti run-*.{json,md} tenere prima di potare i piu vecchi
TRAIN_REQ = os.path.join(REPO, "tools", "anima", "train_requests.json")   # file richieste della scheda Allenamento
TRAIN_PY = os.path.join("tools", "train_wiki.py")                          # runner allenamento (relativo a REPO)

# Pausa fra due test che martellano il device reale (categoria device-load), così heap+WiFi del
# Cardputer (no-PSRAM) rientrano prima della raffica successiva. Saltata se il device ha fatto SKIP.
DEVICE_COOLDOWN_S = 4

DOT = {"pending": "○", "running": "◐", "pass": "●", "fail": "●", "skip": "◌", "error": "▲"}
CL = {"pending": "#8a8a8a", "running": "#d6a100", "pass": "#1faa59", "fail": "#e5484d", "skip": "#8a8a8a",
      "error": "#e5484d", "bg": "#0f1115", "panel": "#171a21", "card": "#1b1f27", "fg": "#e6e6e6",
      "muted": "#9aa0aa", "accent": "#4c9aff", "row": "#1b1f27", "good": "#1faa59", "warn": "#d6a100", "bad": "#e5484d"}


def load_registry():
    with open(REGISTRY, "r", encoding="utf-8") as f:
        return json.load(f)


class Tip:
    """A lightweight hover tooltip (dark, wrapped). Attach to a widget; shows after a short delay."""
    def __init__(self, widget, text, delay=450):
        self.w, self.text, self.delay, self.id, self.tip = widget, text, delay, None, None

    def bind(self, widget):
        widget.bind("<Enter>", self._enter, add="+")
        widget.bind("<Leave>", self._leave, add="+")
        widget.bind("<ButtonPress>", self._leave, add="+")
        return self

    def _enter(self, _e=None):
        self._cancel()
        self.id = self.w.after(self.delay, self._show)

    def _leave(self, _e=None):
        self._cancel(); self._hide()

    def _cancel(self):
        if self.id:
            try: self.w.after_cancel(self.id)
            except Exception: pass
            self.id = None

    def _show(self):
        if self.tip or not self.text:
            return
        x, y = self.w.winfo_pointerx() + 14, self.w.winfo_pointery() + 20
        self.tip = tw = tk.Toplevel(self.w)
        tw.wm_overrideredirect(True)
        tw.wm_geometry(f"+{x}+{y}")
        tw.configure(bg="#2a2f3a")
        tk.Label(tw, text=self.text, bg="#0c0e12", fg="#e6e6e6", font=("Segoe UI", 9), justify="left",
                 wraplength=340, padx=9, pady=7).pack(padx=1, pady=1)

    def _hide(self):
        if self.tip:
            self.tip.destroy(); self.tip = None


class TestLab(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("ANIMA Test Lab · health monitor")
        self.geometry("1240x820")
        self.minsize(1160, 700)   # sotto questa larghezza la toolbar si schiaccerebbe (campi device irraggiungibili)
        self.configure(bg=CL["bg"])
        self.reg = load_registry()
        self.reg_tests = {t["id"]: t for t in self.reg["tests"]}
        self.health_defs = self.reg.get("health", [])
        self.tests = {t["id"]: dict(t, status="pending", summary="", output="") for t in self.reg["tests"]}
        self.cats = {c["id"]: c for c in self.reg["categories"]}
        self.q = queue.Queue()
        self.worker = None
        self.stop_flag = threading.Event()
        self.item_for = {}
        self.cat_node = {}
        self.prev_health = self._last_snapshot()
        self._style()
        self._ui()
        self._populate()
        self._render_dashboard()
        self.after(80, self._drain)
        self.after(1000, self._tick)   # orologio/indicatore di corsa: avanza anche fra una query e l'altra

    # ---- style ---------------------------------------------------------------------------------
    def _style(self):
        self.mono = tkfont.Font(family="Consolas", size=10)
        st = ttk.Style(self)
        try: st.theme_use("clam")
        except tk.TclError: pass
        st.configure("TNotebook", background=CL["bg"], borderwidth=0)
        st.configure("TNotebook.Tab", background=CL["panel"], foreground=CL["muted"], padding=(16, 7), font=("Segoe UI", 10, "bold"))
        st.map("TNotebook.Tab", background=[("selected", CL["card"])], foreground=[("selected", CL["fg"])])
        st.configure("Treeview", background=CL["row"], fieldbackground=CL["row"], foreground=CL["fg"], rowheight=24, borderwidth=0, font=("Segoe UI", 10))
        st.configure("Treeview.Heading", background=CL["panel"], foreground=CL["muted"], borderwidth=0, font=("Segoe UI", 9, "bold"))
        st.map("Treeview", background=[("selected", "#27406b")], foreground=[("selected", "#ffffff")])
        st.configure("TProgressbar", troughcolor=CL["panel"], background=CL["accent"], borderwidth=0)

    # ---- tooltips ------------------------------------------------------------------------------
    def _descendants(self, w):
        out = [w]
        for c in w.winfo_children():
            out += self._descendants(c)
        return out

    def _tip(self, widget, text):
        """Attach a hover tooltip to a widget AND all its children (so hovering a card's number works too)."""
        t = Tip(widget, text)
        for w in self._descendants(widget):
            t.bind(w)
        return t

    # ---- layout --------------------------------------------------------------------------------
    def _ui(self):
        top = tk.Frame(self, bg=CL["bg"]); top.pack(side="top", fill="x", padx=12, pady=(10, 4))
        tk.Label(top, text="ANIMA", bg=CL["bg"], fg=CL["fg"], font=("Segoe UI", 17, "bold")).pack(side="left")
        tk.Label(top, text="test lab · health monitor", bg=CL["bg"], fg=CL["muted"], font=("Segoe UI", 12)).pack(side="left", padx=8)
        self.headline = tk.Label(top, text="", bg=CL["bg"], fg=CL["muted"], font=("Segoe UI", 12, "bold")); self.headline.pack(side="right")
        # Indicatore di corsa SEMPRE VISIBILE (su ogni scheda): lampeggia mentre i test girano.
        self.runpill = tk.Label(top, text="○ pronto", bg=CL["bg"], fg=CL["muted"], font=("Segoe UI", 11, "bold"))
        self.runpill.pack(side="right", padx=14)
        self._run_blink = False
        self._tip(self.headline, "Stato di salute di ANIMA dopo l'ultima corsa: «in salute» = 0 allucinazioni E tutti i test "
                                 "verdi. Altrimenti segnala allucinazioni o test rossi.")

        self.rebuild = tk.BooleanVar(value=True)
        self.only_nl = tk.BooleanVar(value=False)
        self.search = tk.StringVar()
        self.device_ip = tk.StringVar(value="192.168.0.166")   # target dei test device-load (iniettato come --url)
        self._device_ip_snap = "192.168.0.166"                 # snapshot preso sul main thread a ogni corsa
        self.device_delay = tk.IntVar(value=12)                # pausa fra query NL sul device (--delay), min 3
        self._device_delay_snap = 12
        bar = tk.Frame(self, bg=CL["bg"]); bar.pack(side="top", fill="x", padx=12, pady=(0, 6))

        def btn(p, text, cmd, tip="", accent=False):
            b = tk.Button(p, text=text, command=cmd, relief="flat", padx=12, pady=5,
                          bg=CL["accent"] if accent else CL["panel"], fg="#ffffff", activebackground="#5aa9ff",
                          activeforeground="#ffffff", font=("Segoe UI", 10, "bold"), cursor="hand2", bd=0)
            b.pack(side="left", padx=(0, 6))
            if tip: self._tip(b, tip)
            return b

        n_anima = sum(1 for t in self.reg["tests"] if t.get("anima"))
        n_nl = sum(1 for t in self.reg["tests"] if t["nl"])
        # I test «device-load» sono gli UNICI che colpiscono il Cardputer reale; tutto il resto gira su PC.
        host_ids = [t["id"] for t in self.reg["tests"] if not self._is_device(t)]
        self._dev_ids = [t["id"] for t in self.reg["tests"] if t["category"] == "device-load"]
        btn(bar, "🧠 ANIMA offline", lambda: self.run([t["id"] for t in self.reg["tests"] if t.get("anima")]), accent=True,
            tip=(f"Esegue SOLO i {n_anima} test della cascata deterministica di ANIMA (M1): le 8 categorie in linguaggio "
                 "naturale + infrastruttura cascata + knowledge-graph. Girano su PC, NON sul Cardputer.\n\nNIENTE modelli "
                 "generativi (esclude forge/WebLLM, anche se mockato), NIENTE test delle app."))
        btn(bar, "▶ Esegui tutti (PC)", lambda: self.run(host_ids),
            tip=(f"Esegue tutti i {len(host_ids)} test che girano su PC: ANIMA + Forge/WebLLM (MockEngine) + suite app + "
                 "build-lint.\n\nNON include i test «📡 device»: uno sweep completo NON carica il Cardputer. "
                 "Per quelli usa il pulsante 📡.\n\nUno skip atteso: forge-download-manager (senza rete/SD)."))
        btn(bar, "🗣 Solo NL", lambda: self.run([t["id"] for t in self.reg["tests"] if t["nl"]]),
            tip=f"Esegue solo i {n_nl} test in linguaggio naturale (il cuore del sistema): anti-allucinazione, routing skill, "
                "conoscenza, ragionamento, matematica, memoria, traduzione, meteo, copilot foglio.\n\nGirano su PC contro "
                "anima.exe: NON contattano il Cardputer, puoi lanciarli tutti senza caricare il device.")
        btn(bar, "📡 Test device", lambda: self.run(self._dev_ids),
            tip=(f"Esegue gli unici {len(self._dev_ids)} test che colpiscono il CARDPUTER REALE all'IP nel campo «device» "
                 "(arbiter load + fs stress).\n\nSono stress test deliberati: fra l'uno e l'altro c'è una pausa di "
                 f"raffreddamento. SKIP puliti se l'IP non risponde. Gli unici che caricano il device."))
        btn(bar, "▶ Selezione", self.run_selected,
            tip="Esegue solo le righe selezionate nell'albero della scheda «Test» (tieni Ctrl/Shift per selezione multipla; "
                "seleziona una categoria per lanciarne tutti i test).")
        btn(bar, "↻ Falliti", lambda: self.run([i for i, t in self.tests.items() if t["status"] in ("fail", "error")]),
            tip="Ri-esegue solo i test risultati ROSSI nell'ultima corsa — utile dopo una correzione, senza rifare tutto.")
        btn(bar, "■ Stop", self.stop, tip="Interrompe la corsa in corso dopo il test attuale (non uccide il processo già avviato).")
        cb = tk.Checkbutton(bar, text="ricompila exe prima", variable=self.rebuild, bg=CL["bg"], fg=CL["muted"], selectcolor=CL["panel"],
                            activebackground=CL["bg"], activeforeground=CL["fg"], font=("Segoe UI", 9)); cb.pack(side="left", padx=8)
        self._tip(cb, "Prima di una corsa ricompila l'eseguibile della cascata (anima.exe) dal firmware, se i sorgenti sono "
                      "cambiati. Tienilo attivo dopo aver modificato il firmware; disattivalo per ripartenze più rapide.")
        self.prog = ttk.Progressbar(bar, mode="determinate", length=220); self.prog.pack(side="right")
        self._tip(self.prog, "Avanzamento: quanti test sono stati eseguiti sul totale.")

        # --- riga DEDICATA ai controlli del Cardputer (sempre visibile e modificabile, non più schiacciata
        #     nella toolbar affollata). Valgono SOLO per i test «device-load» (📡); gli altri li ignorano. ---
        devbar = tk.Frame(self, bg=CL["card"]); devbar.pack(side="top", fill="x", padx=12, pady=(0, 6))
        tk.Label(devbar, text="📡 Cardputer", bg=CL["card"], fg=CL["warn"], font=("Segoe UI", 10, "bold")).pack(side="left", padx=(10, 8), pady=6)
        tk.Label(devbar, text="IP / URL:", bg=CL["card"], fg=CL["muted"], font=("Segoe UI", 9)).pack(side="left", padx=(0, 4))
        ipent = tk.Entry(devbar, textvariable=self.device_ip, bg=CL["panel"], fg=CL["fg"], insertbackground=CL["fg"],
                         relief="flat", width=22, font=("Segoe UI", 10)); ipent.pack(side="left", ipady=3)
        tk.Label(devbar, text="pausa NL (s):", bg=CL["card"], fg=CL["muted"], font=("Segoe UI", 9)).pack(side="left", padx=(16, 4))
        delayspin = tk.Spinbox(devbar, from_=3, to=120, textvariable=self.device_delay, width=4,
                               bg=CL["panel"], fg=CL["fg"], insertbackground=CL["fg"], relief="flat",
                               buttonbackground=CL["panel"], font=("Segoe UI", 10), justify="center")
        delayspin.pack(side="left", ipady=2)
        tk.Label(devbar, text="vale solo per i test 📡 device (gli altri girano su PC)", bg=CL["card"],
                 fg=CL["muted"], font=("Segoe UI", 8, "italic")).pack(side="left", padx=12)
        self._tip(ipent, "IP (o URL) del Cardputer per i test «📡 device».\n\nViene passato come --url SOLO a quei test; "
                         "gli altri (host/PC) lo ignorano. Vuoto = usa il default dello script.\n\n"
                         "Default 192.168.0.166. I test device SKIPpano puliti se l'IP non risponde.")
        self._tip(delayspin, "Pausa fra una query NL e l'altra nel test «NL soak (device)» (secondi).\n\n"
                             "Dà a heap+WiFi del Cardputer (no-PSRAM) il tempo di rientrare fra una richiesta e l'altra.\n"
                             "Default 12s · minimo 3s (valori più bassi vengono riportati a 3).")

        self.nb = ttk.Notebook(self); self.nb.pack(side="top", fill="both", expand=True, padx=12, pady=(0, 4))
        self.tab_dash = tk.Frame(self.nb, bg=CL["bg"]); self.nb.add(self.tab_dash, text="  Panoramica  ")
        self.tab_test = tk.Frame(self.nb, bg=CL["bg"]); self.nb.add(self.tab_test, text="  Test  ")
        self.tab_train = tk.Frame(self.nb, bg=CL["bg"]); self.nb.add(self.tab_train, text="  Allenamento  ")
        self.tab_trend = tk.Frame(self.nb, bg=CL["bg"]); self.nb.add(self.tab_trend, text="  Andamento  ")
        self.nb.bind("<<NotebookTabChanged>>",
                     lambda e: self._render_trends() if self.nb.select() == str(self.tab_trend) else None)

        self._build_test_tab()
        self._build_train_tab()
        self.status = tk.Label(self, text="pronto", bg=CL["panel"], fg=CL["muted"], anchor="w", font=("Segoe UI", 9)); self.status.pack(side="bottom", fill="x")

    def _build_test_tab(self):
        body = tk.Frame(self.tab_test, bg=CL["bg"]); body.pack(fill="both", expand=True)
        ctrl = tk.Frame(body, bg=CL["bg"]); ctrl.pack(side="top", fill="x", pady=(6, 4))
        nlcb = tk.Checkbutton(ctrl, text="solo categorie NL", variable=self.only_nl, command=self._populate, bg=CL["bg"], fg=CL["muted"],
                              selectcolor=CL["panel"], activebackground=CL["bg"], activeforeground=CL["fg"], font=("Segoe UI", 9)); nlcb.pack(side="left")
        self._tip(nlcb, "Mostra nell'albero solo le categorie in linguaggio naturale (nasconde forge/app/build-lint). "
                        "È un filtro di VISTA: non cambia cosa eseguono i pulsanti in alto.")
        tk.Label(ctrl, text="filtro:", bg=CL["bg"], fg=CL["muted"], font=("Segoe UI", 9)).pack(side="left", padx=(12, 2))
        ent = tk.Entry(ctrl, textvariable=self.search, bg=CL["panel"], fg=CL["fg"], insertbackground=CL["fg"], relief="flat", width=26, font=("Segoe UI", 10)); ent.pack(side="left")
        self._tip(ent, "Filtra i test per nome o per «cosa verifica». Vuoto = mostra tutto.")
        self.search.trace_add("write", lambda *_: self._populate())
        tk.Label(ctrl, text="🗣 NL su PC      📡 device reale (Cardputer)", bg=CL["bg"], fg=CL["muted"],
                 font=("Segoe UI", 9)).pack(side="right", padx=(0, 4))

        left = tk.Frame(body, bg=CL["bg"]); left.pack(side="left", fill="both", expand=True)
        self.tree = ttk.Treeview(left, columns=("status", "summary"), show="tree headings", selectmode="extended")
        self.tree.heading("#0", text="Test"); self.tree.column("#0", width=360, anchor="w")
        self.tree.heading("status", text="Esito"); self.tree.column("status", width=80, anchor="center")
        self.tree.heading("summary", text="Riassunto"); self.tree.column("summary", width=380, anchor="w")
        vs = ttk.Scrollbar(left, orient="vertical", command=self.tree.yview); self.tree.configure(yscrollcommand=vs.set)
        self.tree.pack(side="left", fill="both", expand=True); vs.pack(side="right", fill="y")
        self.tree.bind("<<TreeviewSelect>>", self._show_output)
        self.tree.bind("<Double-1>", lambda e: self.run_selected())
        self._tt = None; self._tt_row = None
        self.tree.bind("<Motion>", self._tree_hover, add="+")
        self.tree.bind("<Leave>", lambda e: self._hide_tt(), add="+")
        for s in DOT: self.tree.tag_configure(s, foreground=CL[s])
        self.tree.tag_configure("cat", font=("Segoe UI", 10, "bold"), foreground=CL["accent"])
        self.tree.tag_configure("catdev", font=("Segoe UI", 10, "bold"), foreground=CL["warn"])  # categoria device reale

        right = tk.Frame(body, bg=CL["panel"], width=470); right.pack(side="right", fill="both"); right.pack_propagate(False)
        # --- intestazione FISSA (non scorre): titolo + badge stato + riquadri contatori + barra + meta + verdetto ---
        hdr = tk.Frame(right, bg=CL["panel"]); hdr.pack(side="top", fill="x", padx=10, pady=(8, 2))
        self.live_title = tk.Label(hdr, text="Output", bg=CL["panel"], fg=CL["fg"], font=("Segoe UI", 11, "bold"), anchor="w")
        self.live_title.pack(side="left")
        self.live_badge = tk.Label(hdr, text="", bg=CL["panel"], fg=CL["muted"], font=("Segoe UI", 9, "bold"))
        self.live_badge.pack(side="right")
        self._cells = tk.Frame(right, bg=CL["panel"])     # riempito on-demand (solo quando arrivano righe per-query)
        self.cell_val = {}
        for key, label, color in (("served", "SERVITE", "good"), ("crash", "CRASH", "bad"),
                                  ("err", "ERRORI", "warn"), ("trap", "TRAP", "accent")):
            c = tk.Frame(self._cells, bg=CL["card"]); c.pack(side="left", fill="both", expand=True, padx=3)
            tk.Label(c, text=label, bg=CL["card"], fg=CL["muted"], font=("Segoe UI", 8, "bold")).pack(anchor="w", padx=8, pady=(4, 0))
            self.cell_val[key] = tk.Label(c, text="0", bg=CL["card"], fg=CL[color], font=("Segoe UI", 16, "bold"))
            self.cell_val[key].pack(anchor="w", padx=8, pady=(0, 5))
        self.live_prog = ttk.Progressbar(right, mode="determinate")
        self.live_prog.pack(side="top", fill="x", padx=10, pady=(2, 3))
        self.live_meta = tk.Label(right, text="", bg=CL["panel"], fg=CL["muted"], font=self.mono, anchor="w", justify="left")
        self.live_meta.pack(side="top", fill="x", padx=10, pady=(0, 2))
        self.live_verdict = tk.Label(right, text="", bg=CL["panel"], fg=CL["muted"], font=("Segoe UI", 10, "bold"), anchor="w")
        self.live_verdict.pack(side="top", fill="x", padx=10, pady=(0, 6))
        # --- log SCORREVOLE colorato ---
        logwrap = tk.Frame(right, bg=CL["panel"]); logwrap.pack(side="top", fill="both", expand=True, padx=(10, 0), pady=(0, 8))
        self.out = tk.Text(logwrap, bg="#0c0e12", fg="#cfd3da", insertbackground=CL["fg"], relief="flat",
                           font=self.mono, wrap="word", padx=8, pady=6)
        self.out.pack(side="left", fill="both", expand=True)
        sc = ttk.Scrollbar(logwrap, orient="vertical", command=self.out.yview); self.out.configure(yscrollcommand=sc.set)
        sc.pack(side="right", fill="y")
        for tag, col in (("good", CL["good"]), ("bad", CL["bad"]), ("warn", CL["warn"]),
                         ("dim", CL["muted"]), ("head", CL["accent"])):
            self.out.tag_configure(tag, foreground=col)

    # ---- training tab --------------------------------------------------------------------------
    def _build_train_tab(self):
        f = tk.Frame(self.tab_train, bg=CL["bg"]); f.pack(fill="both", expand=True, padx=4, pady=6)
        tk.Label(f, text="Allenamento · domande stile Wikipedia", bg=CL["bg"], fg=CL["fg"],
                 font=("Segoe UI", 13, "bold")).pack(anchor="w", padx=8)
        tk.Label(f, text="Incolla un elenco di richieste (array JSON, JSONL o una domanda per riga). «▶ Esegui» le manda "
                         "al Cardputer (IP nella riga 📡 in alto · cadenza = «pausa NL») UNA per volta, in sola lettura, e "
                         "segna cosa ANIMA risponde e cosa lascia vuoto. I «buchi» (domande senza risposta) finiscono in "
                         "reports/train-gaps-*.json = gli obiettivi di training. Risultati live nella scheda «Test».",
                 bg=CL["bg"], fg=CL["muted"], font=("Segoe UI", 9), wraplength=980, justify="left").pack(anchor="w", padx=8, pady=(2, 8))
        bar = tk.Frame(f, bg=CL["bg"]); bar.pack(side="top", fill="x", padx=6)

        def b(text, cmd, tip="", accent=False):
            x = tk.Button(bar, text=text, command=cmd, relief="flat", padx=12, pady=5,
                          bg=CL["accent"] if accent else CL["panel"], fg="#ffffff", activebackground="#5aa9ff",
                          activeforeground="#ffffff", font=("Segoe UI", 10, "bold"), cursor="hand2", bd=0)
            x.pack(side="left", padx=(0, 6))
            if tip: self._tip(x, tip)
            return x
        b("▶ Esegui allenamento", self._train_run, accent=True,
          tip="Salva l'elenco e lo esegue sul Cardputer (vedi i risultati live nella scheda «Test»).")
        b("⬇ Scarica esempio", self._train_example,
          tip="Carica nell'area sotto un elenco di esempio con tante domande wiki (IT+EN), pronto da eseguire o modificare.")
        b("⧉ Copia prompt generatore", self._train_copy_prompt,
          tip="Copia negli appunti un prompt PRONTO da incollare in un LLM (ChatGPT/Claude) per generare NUOVE richieste "
              "nello stesso formato. Chiede «quante» domande e allega l'elenco già presente come «da non ripetere».")
        tk.Label(bar, text="quante:", bg=CL["bg"], fg=CL["muted"], font=("Segoe UI", 9)).pack(side="left", padx=(14, 3))
        self.train_n = tk.IntVar(value=200)
        tk.Spinbox(bar, from_=10, to=2000, increment=50, textvariable=self.train_n, width=6, bg=CL["panel"],
                   fg=CL["fg"], insertbackground=CL["fg"], relief="flat", buttonbackground=CL["panel"],
                   font=("Segoe UI", 10), justify="center").pack(side="left", ipady=1)
        self.train_count = tk.Label(bar, text="", bg=CL["bg"], fg=CL["muted"], font=("Segoe UI", 9)); self.train_count.pack(side="left", padx=12)

        wrap = tk.Frame(f, bg=CL["bg"]); wrap.pack(side="top", fill="both", expand=True, padx=6, pady=(8, 6))
        self.train_text = tk.Text(wrap, bg="#0c0e12", fg="#cfd3da", insertbackground=CL["fg"], relief="flat",
                                  font=self.mono, wrap="word", padx=8, pady=6, undo=True)
        self.train_text.pack(side="left", fill="both", expand=True)
        ts = ttk.Scrollbar(wrap, orient="vertical", command=self.train_text.yview)
        self.train_text.configure(yscrollcommand=ts.set); ts.pack(side="right", fill="y")
        self.train_text.bind("<<Modified>>", self._train_on_edit)
        try:
            if os.path.exists(TRAIN_REQ):
                self.train_text.insert("1.0", open(TRAIN_REQ, encoding="utf-8").read())
        except OSError:
            pass
        self._train_update_count()

    @staticmethod
    def _train_parse_count(txt):
        """Quante richieste contiene il testo (array JSON → len; altrimenti righe non-vuote/non-commento)."""
        if not txt.strip():
            return 0
        try:
            d = json.loads(txt)
            if isinstance(d, list):
                return len(d)
        except Exception:
            pass
        return sum(1 for l in txt.splitlines() if l.strip() and not l.strip().startswith("//"))

    def _train_update_count(self):
        n = self._train_parse_count(self.train_text.get("1.0", "end"))
        self.train_count.config(text=f"{n} richieste" if n else "vuoto — incolla un elenco o «⬇ Scarica esempio»")

    def _train_on_edit(self, _e):
        if self.train_text.edit_modified():
            self.train_text.edit_modified(False)
            self._train_update_count()

    def _train_subprocess(self, extra_args):
        """Chiama il runner allenamento per attività rapide (esempio/prompt). Ritorna (ok, stdout)."""
        env = {**os.environ, "PYTHONUTF8": "1", "PYTHONIOENCODING": "utf-8"}
        try:
            p = subprocess.run([sys.executable, TRAIN_PY, *extra_args], cwd=REPO, capture_output=True,
                               text=True, encoding="utf-8", env=env, timeout=30)
            return p.returncode == 0, (p.stdout or "")
        except Exception as e:
            return False, str(e)

    def _train_example(self):
        path = os.path.join(REPO, "tools", "anima", "train_requests.example.json")
        ok, out = self._train_subprocess(["--example", path])
        if not ok:
            self.status.config(text=f"esempio KO: {out.strip()[:80]}"); return
        try:
            content = open(path, encoding="utf-8").read()
        except OSError as e:
            self.status.config(text=f"esempio KO: {e}"); return
        self.train_text.delete("1.0", "end"); self.train_text.insert("1.0", content)
        self._train_update_count()
        self.status.config(text=f"esempio caricato — {self._train_parse_count(content)} casi (modificabili)")

    @staticmethod
    def _train_questions(txt):
        """Estrae la lista delle domande (q) dal testo: array JSON / JSONL / una per riga."""
        txt = txt.strip()
        if not txt:
            return []
        out = []
        try:
            d = json.loads(txt)
            if isinstance(d, list):
                for o in d:
                    if isinstance(o, dict) and o.get("q"): out.append(str(o["q"]).strip())
                    elif isinstance(o, str) and o.strip(): out.append(o.strip())
                return out
        except Exception:
            pass
        for l in txt.splitlines():
            l = l.strip()
            if not l or l.startswith("//"):
                continue
            if l.startswith("{"):
                try:
                    o = json.loads(l)
                    if o.get("q"): out.append(str(o["q"]).strip()); continue
                except Exception:
                    pass
            out.append(l)
        return out

    def _train_copy_prompt(self):
        try: n = max(1, int(self.train_n.get()))
        except (tk.TclError, ValueError): n = 200
        ok, out = self._train_subprocess(["--print-prompt", "--count", str(n)])
        if not ok or not out.strip():
            self.status.config(text="copia prompt KO"); return
        prompt = out.strip()
        avoid = self._train_questions(self.train_text.get("1.0", "end"))
        if avoid:
            shown = avoid[:400]                 # cap: non gonfiare il prompt all'infinito
            prompt += ("\n\nDA NON USARE — queste domande sono GIÀ in elenco, generane solo di NUOVE e diverse:\n"
                       + "\n".join(f"- {q}" for q in shown))
            if len(avoid) > len(shown):
                prompt += f"\n(…e altre {len(avoid) - len(shown)} già presenti: evitale comunque tutte)"
        self.clipboard_clear(); self.clipboard_append(prompt)
        self.status.config(text=f"prompt per {n} richieste copiato ({len(avoid)} da non ripetere) — incollalo in un LLM")

    def _train_run(self):
        if "train-wiki-device" not in self.tests:
            self.status.config(text="test allenamento assente dal registry"); return
        if self.worker and self.worker.is_alive():
            self.status.config(text="già in esecuzione…"); return
        txt = self.train_text.get("1.0", "end").strip()
        if not txt:
            self.status.config(text="incolla prima un elenco di richieste (o «⬇ Scarica esempio»)"); return
        try:
            with open(TRAIN_REQ, "w", encoding="utf-8") as fp:
                fp.write(txt)
        except OSError as e:
            self.status.config(text=f"non riesco a salvare {TRAIN_REQ}: {e}"); return
        n = self._train_parse_count(txt)
        self.status.config(text=f"avvio allenamento: {n} richieste → risultati live nella scheda «Test»")
        self.run(["train-wiki-device"])

    # ---- dashboard -----------------------------------------------------------------------------
    def _render_dashboard(self):
        for w in self.tab_dash.winfo_children(): w.destroy()
        h = self._compute_health()
        cards = tk.Frame(self.tab_dash, bg=CL["bg"]); cards.pack(side="top", fill="x", pady=(10, 6))
        for hd in self.health_defs:
            val, sub, color, arrow = self._health_card_value(hd, h)
            self._card(cards, hd["label"], val, sub, color, arrow, hd.get("hint", ""))
        # per-category health grid
        grid = tk.Frame(self.tab_dash, bg=CL["bg"]); grid.pack(side="top", fill="both", expand=True, padx=2, pady=6)
        tk.Label(grid, text="Salute per categoria", bg=CL["bg"], fg=CL["muted"], font=("Segoe UI", 10, "bold")).pack(anchor="w", padx=6, pady=(4, 6))
        wrap = tk.Frame(grid, bg=CL["bg"]); wrap.pack(fill="both", expand=True)
        col = 0; rowf = None
        for i, c in enumerate(self.reg["categories"]):
            mem = [t for t in self.reg["tests"] if t["category"] == c["id"]]
            if not mem: continue
            if i % 4 == 0: rowf = tk.Frame(wrap, bg=CL["bg"]); rowf.pack(fill="x")
            self._cat_chip(rowf, c, mem)
        self.headline.config(**self._headline(h))

    def _card(self, parent, title, value, sub, color, arrow, hint):
        f = tk.Frame(parent, bg=CL["card"], padx=16, pady=12); f.pack(side="left", fill="both", expand=True, padx=6)
        tk.Label(f, text=title.upper(), bg=CL["card"], fg=CL["muted"], font=("Segoe UI", 9, "bold")).pack(anchor="w")
        row = tk.Frame(f, bg=CL["card"]); row.pack(anchor="w", pady=(2, 0))
        tk.Label(row, text=value, bg=CL["card"], fg=color, font=("Segoe UI", 26, "bold")).pack(side="left")
        if arrow: tk.Label(row, text=arrow, bg=CL["card"], fg=CL["muted"], font=("Segoe UI", 13)).pack(side="left", padx=(8, 0), pady=(8, 0))
        tk.Label(f, text=sub, bg=CL["card"], fg=CL["muted"], font=("Segoe UI", 9)).pack(anchor="w")
        if hint:
            self._tip(f, hint + ("\n\n▲/▼ = variazione rispetto all'esecuzione completa precedente." if arrow else ""))

    def _cat_chip(self, parent, c, mem):
        g = sum(1 for t in mem if self.tests[t["id"]]["status"] == "pass")
        r = sum(1 for t in mem if self.tests[t["id"]]["status"] in ("fail", "error"))
        done = g + r + sum(1 for t in mem if self.tests[t["id"]]["status"] == "skip")
        color = CL["good"] if (g == len(mem)) else (CL["bad"] if r else CL["muted"])
        f = tk.Frame(parent, bg=CL["panel"], padx=10, pady=7); f.pack(side="left", fill="both", expand=True, padx=4, pady=4)
        dev = c["id"] == "device-load"
        tag = "📡 " if dev else ("🗣 " if c["nl"] else "")
        tk.Label(f, text=f"{tag}{c['label']}", bg=CL["panel"], fg=(CL["warn"] if dev else CL["fg"]),
                 font=("Segoe UI", 9, "bold"), anchor="w").pack(anchor="w")
        bar = tk.Frame(f, bg="#0c0e12", height=6); bar.pack(fill="x", pady=(4, 3))
        frac = (g / len(mem)) if mem else 0
        tk.Frame(bar, bg=color, height=6, width=max(2, int(frac * 220))).place(x=0, y=0)
        tk.Label(f, text=f"{g}/{len(mem)}" + ("  ✓" if g == len(mem) else (f"  ✗{r}" if r else f"  {done}/{len(mem)}")),
                 bg=CL["panel"], fg=color, font=("Segoe UI", 9)).pack(anchor="w")
        anima = "  •  fa parte di «ANIMA offline»" if c.get("anima") else "  •  esclusa da «ANIMA offline» (app/modelli)"
        where = ("\n\n📡 USA IL CARDPUTER REALE (IP nel campo «device»). Esclusa da «Esegui tutti»: lanciala col pulsante 📡."
                 if dev else "\n\nGira su PC (non tocca il Cardputer).")
        self._tip(f, f"{c['label']}\n\n{c.get('desc', '')}{anima}{where}\n\nVerdi: {g}/{len(mem)}" + (f" · rossi: {r}" if r else ""))

    def _health_card_value(self, hd, h):
        v = h[hd["id"]]
        arrow = self._trend_arrow(hd["id"], v)
        if hd.get("special") == "green":
            g, tot = v
            color = CL["good"] if (tot and g == tot) else (CL["warn"] if g else CL["muted"])
            return f"{g}/{tot}", "test passati", color, arrow
        goal = hd.get("goal")
        if goal is not None:
            color = CL["good"] if v == goal else CL["bad"]
            return str(v), ("✓ a posto" if v == goal else "⚠ da correggere"), color, arrow
        return f"{v:,}".replace(",", "."), "richieste verificate", CL["accent"], arrow

    def _trend_arrow(self, hid, v):
        prev = self.prev_health.get(hid) if self.prev_health else None
        cur = v[0] if isinstance(v, tuple) else v
        if prev is None: return ""
        p = prev[0] if isinstance(prev, (list, tuple)) else prev
        if cur > p: return f"▲ +{cur - p}"
        if cur < p: return f"▼ {cur - p}"
        return "▬"

    def _headline(self, h):
        hall = h["hallucinations"]; g, tot = h["green"]
        if tot == 0: return {"text": "premi ▶ Esegui tutti (PC)", "fg": CL["muted"]}
        if hall == 0 and g == tot:
            return {"text": f"● ANIMA in salute — 0 allucinazioni · {self._fmt(h['nl_cases'])} casi NL · {g}/{tot} verdi", "fg": CL["good"]}
        if hall:
            return {"text": f"⚠ {hall} allucinazioni rilevate", "fg": CL["bad"]}
        return {"text": f"⚠ {tot - g} test rossi", "fg": CL["bad"]}

    @staticmethod
    def _fmt(n): return f"{n:,}".replace(",", ".")

    # ---- metrics + health ----------------------------------------------------------------------
    def _extract(self, tid):
        out = self.tests[tid]["output"] or ""
        vals = {}
        for m in (self.reg_tests[tid].get("metrics") or []):
            try: rx = re.compile(m["re"], re.I)
            except re.error: continue
            ms = list(rx.finditer(out))
            if not ms: continue
            if m.get("agg") == "sum":
                v = sum(sum(int(g) for g in mm.groups() if g and g.isdigit()) for mm in ms)
            else:
                v = int(ms[-1].group(1))
            vals[m["k"]] = vals.get(m["k"], 0) + v
        return vals

    def _compute_health(self):
        per = {}
        for tid in self.tests:
            for k, v in self._extract(tid).items():
                per[k] = per.get(k, 0) + v
        res = {}
        for hd in self.health_defs:
            if hd.get("special") == "green":
                g = sum(1 for t in self.tests.values() if t["status"] == "pass")
                tot = sum(1 for t in self.tests.values() if t["status"] in ("pass", "fail", "error"))
                res[hd["id"]] = (g, tot)
            else:
                res[hd["id"]] = per.get(hd["metric"], 0)
        return res

    # ---- history + trends ----------------------------------------------------------------------
    def _last_snapshot(self):
        try:
            with open(HISTORY, "r", encoding="utf-8") as f:
                lines = [l for l in f if l.strip()]
            if not lines: return {}
            return json.loads(lines[-1]).get("health", {})
        except OSError:
            return {}

    def _append_history(self):
        h = self._compute_health()
        snap = {"ts": datetime.now().isoformat(timespec="seconds"),
                "health": {k: (list(v) if isinstance(v, tuple) else v) for k, v in h.items()}}
        try:
            with open(HISTORY, "a", encoding="utf-8") as f:
                f.write(json.dumps(snap) + "\n")
        except OSError:
            pass

    # ---- per-run reports (machine-readable, versioned, + latest pointer) -----------------------
    # Scopo: dopo ogni corsa lasciare una traccia che un'altra sessione (umano o agente) possa
    # rileggere SENZA rifare i test — esito per-test, durate, e l'output dei falliti per diagnosi.
    def _write_report(self, ids):
        ids = [i for i in (ids or []) if i in self.tests]
        if not ids: return None
        items = [self.tests[i] for i in ids]
        cats = {t["category"] for t in items}
        scope = ("device" if cats == {"device-load"} else
                 ("full-pc" if len(ids) >= 20 else "partial"))
        cnt = lambda s: sum(1 for t in items if t["status"] == s)
        h = self._compute_health()
        ts = datetime.now()
        report = {
            "ts": ts.isoformat(timespec="seconds"),
            "scope": scope,
            "device_ip": (self._device_ip_snap or None) if "device-load" in cats else None,
            "counts": {"total": len(items), "pass": cnt("pass"), "fail": cnt("fail"),
                       "error": cnt("error"), "skip": cnt("skip")},
            "health": {k: (list(v) if isinstance(v, tuple) else v) for k, v in h.items()},
            "tests": [{"id": t["id"], "label": t["label"], "category": t["category"],
                       "status": t["status"], "summary": t.get("summary", ""),
                       "duration_s": round(t.get("duration", 0.0), 2),
                       "cmd": f"{t['cmd']} {' '.join(self._args_for(t))}"} for t in items],
            # output completo (troncato) SOLO dei falliti: è ciò che serve per diagnosticare a freddo
            "failures": [{"id": t["id"], "label": t["label"], "category": t["category"],
                          "summary": t.get("summary", ""), "output": (t.get("output", "") or "")[-6000:]}
                         for t in items if t["status"] in ("fail", "error")],
        }
        os.makedirs(REPORTS, exist_ok=True)
        stamp = ts.strftime("%Y%m%d-%H%M%S")
        path = os.path.join(REPORTS, f"run-{stamp}.json")
        self._dump_json(path, report)
        self._dump_json(os.path.join(REPORTS, "latest.json"), report)   # puntatore "ultimo" sempre aggiornato
        md = self._report_md(report)
        self._dump_text(os.path.join(REPORTS, f"run-{stamp}.md"), md)
        self._dump_text(os.path.join(REPORTS, "latest.md"), md)
        # indice append-only: una riga per corsa → "qual è l'ultimo" e storico in colpo d'occhio
        try:
            with open(os.path.join(REPORTS, "index.jsonl"), "a", encoding="utf-8") as f:
                f.write(json.dumps({"ts": report["ts"], "scope": scope, "file": f"run-{stamp}.json",
                                    "counts": report["counts"]}, ensure_ascii=False) + "\n")
        except OSError:
            pass
        self._prune_reports()
        return path

    def _report_md(self, r):
        c = r["counts"]
        head = (r["ts"] + (f"  ·  device {r['device_ip']}" if r["device_ip"] else ""))
        L = [f"# Test Lab — {head}", "",
             f"**Ambito:** `{r['scope']}`  ·  ✅ {c['pass']} · ❌ {c['fail']} · ⚠ {c['error']} · ⏭ {c['skip']}  (su {c['total']})", ""]
        hall = r["health"].get("hallucinations")
        if hall is not None:
            L.append(f"**Allucinazioni:** {hall}  {'✓' if hall == 0 else '⚠'}")
        grn = r["health"].get("green")
        if isinstance(grn, list) and len(grn) == 2:
            L.append(f"**Verdi:** {grn[0]}/{grn[1]}")
        L.append("")
        if r["failures"]:
            L.append("## Falliti (per diagnosi)")
            for fdef in r["failures"]:
                tail = next((ln for ln in reversed((fdef["output"] or "").splitlines()) if ln.strip()), fdef["summary"])
                L.append(f"- **{fdef['label']}** ({fdef['category']}) — {tail.strip()[:160]}")
            L.append("")
        else:
            L.append("_Nessun fallimento: tutti i test eseguiti sono verdi o saltati._")
        slow = sorted(r["tests"], key=lambda t: t["duration_s"], reverse=True)[:5]
        if slow and slow[0]["duration_s"] > 0:
            L.append("## Più lenti")
            for t in slow:
                L.append(f"- {t['label']} — {t['duration_s']}s")
        return "\n".join(L) + "\n"

    @staticmethod
    def _dump_json(path, obj):
        try:
            with open(path, "w", encoding="utf-8") as f:
                json.dump(obj, f, ensure_ascii=False, indent=2)
        except OSError:
            pass

    @staticmethod
    def _dump_text(path, text):
        try:
            with open(path, "w", encoding="utf-8") as f:
                f.write(text)
        except OSError:
            pass

    @staticmethod
    def _prune_reports():
        try:
            runs = sorted(g for g in os.listdir(REPORTS) if g.startswith("run-") and g.endswith(".json"))
        except OSError:
            return
        for old in runs[:-KEEP_REPORTS]:
            for ext in (".json", ".md"):
                try: os.remove(os.path.join(REPORTS, old[:-5] + ext))
                except OSError: pass

    def _render_trends(self):
        for w in self.tab_trend.winfo_children(): w.destroy()
        try:
            with open(HISTORY, "r", encoding="utf-8") as f:
                runs = [json.loads(l) for l in f if l.strip()]
        except OSError:
            runs = []
        if not runs:
            tk.Label(self.tab_trend, text="Nessuno storico ancora — esegui tutti i test per registrare il primo punto.",
                     bg=CL["bg"], fg=CL["muted"], font=("Segoe UI", 11)).pack(pady=30); return
        tk.Label(self.tab_trend, text=f"Andamento su {len(runs)} esecuzioni", bg=CL["bg"], fg=CL["muted"],
                 font=("Segoe UI", 10, "bold")).pack(anchor="w", padx=8, pady=(10, 6))
        for hd in self.health_defs:
            series = []
            for r in runs:
                v = r.get("health", {}).get(hd["id"])
                if isinstance(v, list): v = (v[0] / v[1]) * 100 if v[1] else 0
                series.append(v if v is not None else 0)
            self._spark(self.tab_trend, hd["label"], series, hd)

    def _spark(self, parent, title, series, hd):
        f = tk.Frame(parent, bg=CL["card"]); f.pack(fill="x", padx=10, pady=6)
        head = tk.Frame(f, bg=CL["card"]); head.pack(fill="x", padx=12, pady=(8, 0))
        last = series[-1] if series else 0
        txt = f"{last:.0f}%" if hd.get("special") == "green" else self._fmt(int(last))
        tk.Label(head, text=title, bg=CL["card"], fg=CL["fg"], font=("Segoe UI", 10, "bold")).pack(side="left")
        tk.Label(head, text=txt, bg=CL["card"], fg=CL["accent"], font=("Segoe UI", 11, "bold")).pack(side="right")
        cv = tk.Canvas(f, bg=CL["card"], height=46, highlightthickness=0); cv.pack(fill="x", padx=12, pady=(2, 10))
        cv.update_idletasks(); W = max(cv.winfo_width(), 600); H = 46
        lo, hi = min(series), max(series)
        rng = (hi - lo) or 1
        n = len(series)
        goal = hd.get("goal")
        col = CL["good"]
        if goal is not None and last != goal: col = CL["bad"]
        pts = []
        for i, v in enumerate(series):
            x = 4 + (i / max(1, n - 1)) * (W - 8)
            y = H - 6 - ((v - lo) / rng) * (H - 14)
            pts += [x, y]
        if len(pts) >= 4: cv.create_line(*pts, fill=col, width=2, smooth=True)
        if pts: cv.create_oval(pts[-2] - 3, pts[-1] - 3, pts[-2] + 3, pts[-1] + 3, fill=col, outline=col)

    # ---- tree populate -------------------------------------------------------------------------
    def _populate(self):
        self.tree.delete(*self.tree.get_children()); self.item_for.clear(); self.cat_node.clear()
        flt = self.search.get().strip().lower()
        for cat in self.reg["categories"]:
            if self.only_nl.get() and not cat["nl"]: continue
            mem = [t for t in self.reg["tests"] if t["category"] == cat["id"]
                   and (not flt or flt in t["label"].lower() or flt in (t.get("verifies") or "").lower())]
            if not mem: continue
            dev = cat["id"] == "device-load"
            tag = "📡 " if dev else ("🗣 " if cat["nl"] else "")
            node = self.tree.insert("", "end", text=f"{tag}{cat['label']}  ({len(mem)})", open=cat["nl"],
                                    tags=(("cat", "catdev") if dev else ("cat",)))
            self.cat_node[cat["id"]] = node
            for t in mem:
                st = self.tests[t["id"]]["status"]
                it = self.tree.insert(node, "end", text="   " + t["label"], values=(DOT[st], self.tests[t["id"]]["summary"]), tags=(st,))
                self.item_for[it] = t["id"]

    # ---- running -------------------------------------------------------------------------------
    def run_selected(self):
        ids = []
        for it in self.tree.selection():
            if it in self.item_for: ids.append(self.item_for[it])
            else:
                for ch in self.tree.get_children(it):
                    if ch in self.item_for: ids.append(self.item_for[ch])
        if ids: self.run(ids)

    def run(self, ids):
        if self.worker and self.worker.is_alive():
            self.status.config(text="già in esecuzione…"); return
        ids = [i for i in ids if i in self.tests]
        if not ids: return
        self.prev_health = self._compute_health() if any(t["status"] != "pending" for t in self.tests.values()) else self._last_snapshot()
        for i in ids: self.tests[i].update(status="pending", summary="")
        self._sync_rows()
        self.stop_flag.clear()
        self._device_ip_snap = self.device_ip.get().strip()   # snapshot on the main thread (Tk vars aren't thread-safe)
        try: self._device_delay_snap = max(3, int(self.device_delay.get()))   # floor 3s, anche se l'utente digita meno
        except (tk.TclError, ValueError): self._device_delay_snap = 12
        self._last_ids = list(ids)        # esattamente cosa è girato in QUESTA corsa → ambito del report
        self._full_run = len(ids) >= 20   # a substantial run (ANIMA-offline / NL / all) records a trend point
        self.worker = threading.Thread(target=self._run_batch, args=(ids,), daemon=True); self.worker.start()

    @staticmethod
    def _is_device(t):
        """Un test colpisce il Cardputer reale se è device-load O ha il flag ui_device (es. allenamento)."""
        return t.get("category") == "device-load" or bool(t.get("ui_device"))

    def _args_for(self, t):
        """Args del registry, più --url <device-ip> per i test che toccano il device (e --delay se ui_delay).
        L'IP/pausa digitati (snapshot sul main thread) sovrascrivono i default dello script; vuoto = li lascia."""
        args = list(t["args"])
        if self._is_device(t) and self._device_ip_snap and "--url" not in args:
            ip = self._device_ip_snap
            args += ["--url", ip if ip.startswith("http") else f"http://{ip}"]
        if t.get("ui_delay") and "--delay" not in args:
            args += ["--delay", str(self._device_delay_snap)]   # pausa/cadenza impostata dalla UI
        return args

    def _stream_proc(self, t, to, on_line):
        """Esegue il test e ne fa lo STREAM dello stdout riga-per-riga (on_line per ogni riga), invece di
        catturare tutto alla fine. Ritorna (returncode, output_completo, timed_out). PYTHONUNBUFFERED forza
        il figlio Python a non bufferizzare lo stdout su pipe (altrimenti niente live). ■ Stop uccide il proc."""
        env = {**os.environ, "PYTHONUTF8": "1", "PYTHONIOENCODING": "utf-8", "PYTHONUNBUFFERED": "1"}
        proc = subprocess.Popen([t["cmd"], *self._args_for(t)], cwd=REPO, stdout=subprocess.PIPE,
                                stderr=subprocess.STDOUT, text=True, bufsize=1, encoding="utf-8",
                                errors="replace", env=env)
        self._cur_proc = proc                   # esposto a stop(): kill IMMEDIATO anche durante una pausa lunga
        timed = {"v": False}
        timer = None
        if to:                                  # to=None (registry timeout_s:null) → nessun timer, soak illimitato
            def _kill():
                timed["v"] = True
                try: proc.kill()
                except Exception: pass
            timer = threading.Timer(to, _kill); timer.start()
        lines = []
        try:
            for line in proc.stdout:
                line = line.rstrip("\n")
                lines.append(line)
                on_line(line)
                if self.stop_flag.is_set():
                    try: proc.kill()
                    except Exception: pass
                    break
        finally:
            try: proc.stdout.close()
            except Exception: pass
            rc = proc.wait()
            if timer: timer.cancel()
            self._cur_proc = None
        return rc, "\n".join(lines), timed["v"]

    def _run_batch(self, ids):
        if self.rebuild.get():
            self.q.put(("status", "ricompilo anima.exe…"))
            try: subprocess.run(["node", "tools/anima-host/anima.mjs", "--ensure"], cwd=REPO, capture_output=True, text=True, timeout=600)
            except Exception as e: self.q.put(("status", f"build: {e}"))
        t0 = time.time()
        for i in ids:
            if self.stop_flag.is_set(): self.q.put(("status", "interrotto")); break
            t = self.tests[i]; self._clear_volatile()
            tgt = f"  📡 → {self._device_ip_snap or 'default'}" if self._is_device(t) else ""
            self.q.put(("set", i, "running", "")); self.q.put(("status", f"▶ {t['label']}{tgt}"))
            self.q.put(("livestart", i))
            status = "error"; ts0 = time.time()
            to = t["timeout_s"] if "timeout_s" in t else 900   # registry può dare null = nessun timeout (soak lunghi)
            try:
                rc, out, timed_out = self._stream_proc(t, to, lambda ln, _i=i: self.q.put(("line", _i, ln)))
                last = next((ln for ln in reversed(out.splitlines()) if ln.strip()), "")
                if self.stop_flag.is_set():
                    self.q.put(("done", i, "error", "interrotto", out, time.time() - ts0))
                elif timed_out:
                    self.q.put(("done", i, "error", "timeout", out, time.time() - ts0))
                else:
                    status = "skip" if ("SKIP" in out and rc == 0) else ("pass" if rc == 0 else "fail")
                    self.q.put(("done", i, status, last.strip()[-90:], out, time.time() - ts0))
            except Exception as e:
                self.q.put(("done", i, "error", str(e)[:80], str(e), time.time() - ts0))
            # Cooldown solo fra test device che hanno DAVVERO girato (no skip), e mai dopo l'ultimo.
            if (t.get("category") == "device-load" and status in ("pass", "fail")
                    and i != ids[-1] and not self.stop_flag.is_set()):
                for s in range(DEVICE_COOLDOWN_S, 0, -1):
                    if self.stop_flag.is_set(): break
                    self.q.put(("status", f"raffreddamento device {s}s…")); time.sleep(1)
        self.q.put(("status", f"fatto in {time.time()-t0:.1f}s"))
        self.q.put(("batchdone", None))

    def stop(self):
        self.stop_flag.set(); self.status.config(text="stop richiesto…")
        p = getattr(self, "_cur_proc", None)        # uccide SUBITO il processo in corso (no attesa fine pausa)
        if p and p.poll() is None:
            try: p.kill()
            except Exception: pass

    @staticmethod
    def _clear_volatile():
        sd = os.path.join(REPO, "tools", "anima-host", "sd", "data", "anima")
        for f in ("units.txt", "session.txt", "telemetry.ndjson", "user.tsv", "user.vec", "user.tsv.tmp",
                  "user.vec.tmp", "profile.tsv", "profile.tsv.tmp", "events.tsv", "events.txt", "calendar.tsv"):
            try: os.remove(os.path.join(sd, f))
            except OSError: pass

    # ---- queue drain ---------------------------------------------------------------------------
    def _drain(self):
        try:
            while True:
                msg = self.q.get_nowait()
                if msg[0] == "status": self.status.config(text=msg[1])
                elif msg[0] == "livestart": self._live_begin(msg[1])
                elif msg[0] == "line": self._live_line(msg[1], msg[2])
                elif msg[0] == "set":
                    _, i, st, su = msg; self.tests[i].update(status=st, summary=su); self._sync_one(i)
                elif msg[0] == "done":
                    _, i, st, su, out, dur = msg
                    self.tests[i].update(status=st, summary=su, output=out, duration=dur); self._sync_one(i)
                    self._live_finish(i, st, su)
                    self._refresh_progress()
                elif msg[0] == "batchdone":
                    self._live_idle()
                    self._render_dashboard()
                    if getattr(self, "_full_run", False): self._append_history()
                    try:
                        rpt = self._write_report(getattr(self, "_last_ids", []))
                        if rpt: self.status.config(text=f"{self.status.cget('text')}  ·  report: {os.path.relpath(rpt, REPO)}")
                    except Exception as e:
                        self.status.config(text=f"{self.status.cget('text')}  ·  report KO: {e}")
        except queue.Empty:
            pass
        self.after(80, self._drain)

    def _refresh_progress(self):
        done = sum(1 for t in self.tests.values() if t["status"] in ("pass", "fail", "error", "skip"))
        self.prog["maximum"] = len(self.tests); self.prog["value"] = done

    def _row_of(self, tid):
        for it, i in self.item_for.items():
            if i == tid: return it
        return None

    def _sync_one(self, tid):
        it = self._row_of(tid)
        if it: self.tree.item(it, values=(DOT[self.tests[tid]["status"]], self.tests[tid]["summary"]), tags=(self.tests[tid]["status"],))

    def _sync_rows(self):
        for tid in self.tests: self._sync_one(tid)
        self._refresh_progress()

    @staticmethod
    def _mmss(sec):
        sec = int(max(0, sec)); return f"{sec // 60:02d}:{sec % 60:02d}"

    def _live_begin(self, tid):
        """Un test parte: porta in vista lo stream e azzera l'intestazione. I riquadri contatori restano
        nascosti finché non arrivano righe per-query (li mostra solo il NL soak); per gli altri test la
        barra resta indeterminata (animata) e il log scorre."""
        try: self.nb.select(self.tab_test)
        except Exception: pass
        t = self.reg_tests.get(tid, {})
        self._live_tid = tid
        self._live_active = True
        self._live_has_q = False
        self._live_t0 = time.time()
        self._live_label = t.get("label", "")
        self._live_stats = {"served": 0, "crash": 0, "err": 0, "trap": 0, "n": 0, "tot": 0}
        dev = self._is_device(t)
        self.live_title.config(text=f"▶ {self._live_label}", fg=CL["warn"] if dev else CL["fg"])
        self.live_verdict.config(text="")
        self._cells.pack_forget()                       # riquadri nascosti finché non c'è una riga [q]
        try: self.live_prog.config(mode="indeterminate"); self.live_prog.start(60)
        except tk.TclError: pass
        self.out.delete("1.0", "end")
        self._render_live()

    def _live_color(self, line):
        u = line.upper()
        if line.startswith("[q] "):
            return "bad" if (" CRASH " in line or " H4" in line or " H5" in line) else \
                   ("warn" if "TRAPPOLA-NON-ASTENUTA" in u else "good")
        if "FAIL" in u or "ABORT" in u or "CRASH" in u: return "bad"
        if "PASS" in u or "LIVENESS OK" in u: return "good"
        if "SKIP" in u or "WARN" in u: return "warn"
        return "dim"

    def _live_update_stats(self, line):
        """Parsa '[q] i/N mark lang tier ms · query' → aggiorna SOLO i contatori (il rendering è separato)."""
        if not line.startswith("[q] "):
            return False
        try:
            tok = line.split(" · ", 1)[0].split()       # ['[q]','i/N','mark','lang','tier','msf']
            i, tot = tok[1].split("/")
            s = self._live_stats
            s["n"], s["tot"] = int(i), int(tot)
            mark = tok[2]
            if mark == "ok": s["served"] += 1
            elif mark == "CRASH": s["crash"] += 1
            elif mark.startswith("H"): s["err"] += 1
            if "trappola-non-astenuta" in line.lower(): s["trap"] += 1
            return True
        except (ValueError, IndexError):
            return False

    def _render_live(self):
        """Disegna l'intestazione viva: badge stato + indicatore globale (lampeggia) + riquadri + barra + meta.
        Chiamato sia all'arrivo di una riga sia dal ticker (così l'orologio avanza fra una query e l'altra)."""
        active = getattr(self, "_live_active", False)
        sym = "●" if getattr(self, "_run_blink", False) else "○"
        s = getattr(self, "_live_stats", {"served": 0, "crash": 0, "err": 0, "trap": 0, "n": 0, "tot": 0})
        el = time.time() - getattr(self, "_live_t0", time.time())
        if active:
            self.live_badge.config(text="ESECUZIONE", fg=CL["warn"])
            tail = f"  ·  {s['n']}/{s['tot']}" if self._live_has_q and s["tot"] else ""
            self.runpill.config(text=f"{sym} {self._live_label}{tail}", fg=CL["warn"])
        if self._live_has_q:
            for k in ("served", "crash", "err", "trap"):
                self.cell_val[k].config(text=str(s[k]))
            eta = (el / s["n"]) * (s["tot"] - s["n"]) if s["n"] else 0
            pct = (100 * s["n"] // s["tot"]) if s["tot"] else 0
            try: self.live_prog.config(value=s["n"], maximum=max(1, s["tot"]))
            except tk.TclError: pass
            self.live_meta.config(text=f"{s['n']}/{s['tot']} ({pct}%)   ETA {self._mmss(eta)}   trascorso {self._mmss(el)}")
        elif active:
            self.live_meta.config(text=f"in esecuzione…   trascorso {self._mmss(el)}")

    def _live_finish(self, tid, status, summary):
        """A test finito: ferma la barra, mostra il verdetto evidenziato (se è il test mostrato live)."""
        if getattr(self, "_live_tid", None) != tid:
            return
        try: self.live_prog.stop(); self.live_prog.config(mode="determinate")
        except tk.TclError: pass
        if self._live_has_q and self._live_stats["tot"]:
            self.live_prog.config(maximum=self._live_stats["tot"], value=self._live_stats["tot"])
        v = {"pass": ("✅ PASS", "good"), "fail": ("❌ FAIL", "bad"), "error": ("⚠ ERRORE", "bad"),
             "skip": ("⏭ SKIP — device non raggiungibile", "warn")}.get(status, (status, "dim"))
        extra = f"   ·   {summary}" if summary else ""
        self.live_verdict.config(text=v[0] + extra, fg=CL[v[1]])
        self.live_badge.config(text=v[0].split()[0], fg=CL[v[1]])

    def _live_idle(self):
        """Nessuna run in corso: indicatore globale a riposo."""
        self._live_active = False
        self.runpill.config(text="○ pronto", fg=CL["muted"])

    def _tick(self):
        """Ogni secondo: fa avanzare orologio/ETA e fa lampeggiare l'indicatore mentre i test girano."""
        if getattr(self, "_live_active", False):
            self._run_blink = not getattr(self, "_run_blink", False)
            self._render_live()
        self.after(1000, self._tick)

    def _live_line(self, tid, line):
        """Una riga di stdout dal test in corso → statistiche in alto + riga colorata nel log."""
        if getattr(self, "_live_tid", None) != tid:
            return
        if self._live_update_stats(line) and not self._live_has_q:
            self._live_has_q = True                     # prima riga per-query: rivela i riquadri + barra a %
            self._cells.pack(side="top", fill="x", padx=8, pady=(2, 4), before=self.live_prog)
            try: self.live_prog.stop(); self.live_prog.config(mode="determinate")
            except tk.TclError: pass
        self._render_live()
        self.out.insert("end", line + "\n", self._live_color(line))
        try:                                  # cap del buffer: i soak NL fanno migliaia di righe
            if int(self.out.index("end-1c").split(".")[0]) > 4000:
                self.out.delete("1.0", "2000.0")
        except (tk.TclError, ValueError):
            pass
        self.out.see("end")

    def _tree_hover(self, e):
        row = self.tree.identify_row(e.y)
        if row == self._tt_row:
            return
        self._tt_row = row; self._hide_tt()
        if row in self.item_for:
            t = self.reg_tests[self.item_for[row]]
            st = self.tests[self.item_for[row]]
            verd = {"pass": "✅ verde", "fail": "❌ rosso", "error": "⚠ errore", "skip": "⏭ saltato",
                    "running": "⏳ in corso", "pending": "○ non eseguito"}.get(st["status"], "")
            tip = (f"{t['label']}   ·   {verd}\n\n{t.get('verifies') or '(nessuna descrizione disponibile)'}"
                   f"\n\nlingua: {t.get('lang', 'na')}   ·   {'fa parte di «ANIMA offline»' if t.get('anima') else 'esclusa da «ANIMA offline»'}"
                   f"\n$ {t['cmd']} {' '.join(t['args'])}\n\nDoppio-click per eseguirlo · click per vederne l'output a destra.")
            self._show_tt(tip)

    def _show_tt(self, text):
        x, y = self.tree.winfo_pointerx() + 16, self.tree.winfo_pointery() + 16
        self._tt = tw = tk.Toplevel(self.tree); tw.wm_overrideredirect(True); tw.wm_geometry(f"+{x}+{y}"); tw.configure(bg="#2a2f3a")
        tk.Label(tw, text=text, bg="#0c0e12", fg="#e6e6e6", font=("Segoe UI", 9), justify="left", wraplength=400, padx=9, pady=7).pack(padx=1, pady=1)

    def _hide_tt(self):
        if self._tt:
            self._tt.destroy(); self._tt = None

    def _show_output(self, _e):
        if self.worker and self.worker.is_alive():
            return                          # una run è in corso: non sovrascrivere lo stream live
        sel = self.tree.selection()
        if not sel or sel[0] not in self.item_for: return
        t = self.tests[self.item_for[sel[0]]]
        self._live_tid = None
        v = {"pass": ("✅ verde", "good"), "fail": ("❌ rosso", "bad"), "error": ("⚠ errore", "bad"),
             "skip": ("⏭ saltato", "warn"), "running": ("⏳ in corso", "warn"),
             "pending": ("○ non eseguito", "dim")}.get(t["status"], (t["status"], "dim"))
        self.live_title.config(text=t["label"], fg=CL["warn"] if self._is_device(t) else CL["fg"])
        self.live_badge.config(text=v[0].split()[0], fg=CL[v[1]])
        self._cells.pack_forget()
        try: self.live_prog.stop(); self.live_prog.config(mode="determinate", maximum=1, value=0)
        except tk.TclError: pass
        self.live_meta.config(text="")
        self.live_verdict.config(text=f"{v[0]}   ·   {t.get('summary', '')}".rstrip(" ·"), fg=CL[v[1]])
        self.out.delete("1.0", "end")
        self.out.insert("end", f"$ {t['cmd']} {' '.join(self._args_for(t))}\n", "dim")
        self.out.insert("end", (t.get("verifies", "") or "") + "\n\n", "dim")
        self.out.insert("end", t["output"] or "(non ancora eseguito)")


if __name__ == "__main__":
    if not os.path.exists(REGISTRY):
        print("registry mancante: `node tools/gen-test-registry.mjs`", file=sys.stderr); sys.exit(2)
    TestLab().mainloop()
