#!/usr/bin/env node
// Native UI screenshot harness (npm run ui:shots).
//
// Compiles the REAL on-device UI sources (launcher_render.cpp, launcher_menu.cpp, app_ui.cpp,
// nucleo_theme.cpp, nucleo_i18n.c) together with the REAL LovyanGFX/M5GFX core the firmware links,
// on the PC with MinGW. The display is an in-memory 240x135 sprite, so every scene renders pixel-
// for-pixel as on the Cardputer — same fonts, same rasterizer, same 8bpp back-buffer — without a
// device or a flash. Output: build/ui-host/shots/*.png + index.html (contact sheet).
//
// Golden gate: tools/ui-host/golden.json holds a hash per scene. A changed scene fails the run and
// its PNG is listed; review it, then accept with `npm run ui:shots -- --update`.
//   node tools/ui-host/run.mjs [--update] [--only <substring>]
import { spawn, execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync, existsSync, statSync, readdirSync, rmSync } from 'node:fs';
import { join, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import zlib from 'node:zlib';
import { readRegistry } from '../launcher-host/apps.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..');
const FW = join(root, 'firmware', 'components');
const GFX = join(root, 'firmware', 'managed_components', 'm5stack__m5gfx', 'src');
const CJSON = 'C:/esp/esp-idf/components/json/cJSON';
const OUT = join(root, 'build', 'ui-host');
const OBJ = join(OUT, 'obj');
const LGFX_OBJ = join(OUT, 'lgfx');
const SHOTS = join(OUT, 'shots');
const GOLDEN = join(here, 'golden.json');

const args = process.argv.slice(2);
const update = args.includes('--update');
const only = args.includes('--only') ? args[args.indexOf('--only') + 1] : null;

const MINGW = 'C:/msys64/mingw64/bin';
const GPP = existsSync(`${MINGW}/g++.exe`) ? `${MINGW}/g++.exe` : 'g++';
const GCC = existsSync(`${MINGW}/gcc.exe`) ? `${MINGW}/gcc.exe` : 'gcc';
const env = { ...process.env, PATH: `${MINGW};${process.env.PATH}` };
if (!existsSync(join(CJSON, 'cJSON.c'))) { console.error(`ui-host: cJSON not found at ${CJSON} (ESP-IDF)`); process.exit(1); }

for (const d of [OBJ, LGFX_OBJ, SHOTS]) mkdirSync(d, { recursive: true });
for (const f of readdirSync(SHOTS)) rmSync(join(SHOTS, f));

// ---- the real app registry -------------------------------------------------------------------------
const { apps } = readRegistry();
const q = (s) => JSON.stringify(s);
const esc = (ch) => (ch === "'" || ch === '\\' ? `'\\${ch}'` : `'${ch}'`);
writeFileSync(join(OUT, 'apps.gen.h'), [
  '// Generated by tools/ui-host/run.mjs from the firmware app definitions. Do not edit.',
  '#pragma once',
  'struct HostApp { const char *id, *name, *cat, *desc; char icon; unsigned short color; bool adv_only; };',
  'static const HostApp HOST_APPS[] = {',
  ...apps.map((a) => `    { ${q(a.id)}, ${q(a.name)}, ${q(a.cat)}, ${q(a.desc)}, ${esc(a.icon)}, 0x${a.color.toString(16)}, ${a.advOnly} },`),
  '};',
  `static const int HOST_APP_N = ${apps.length};`,
  '',
].join('\n'));

// ---- compile -------------------------------------------------------------------------------------------
const INC = [
  '-I', join(here, 'shim'), '-I', GFX, '-I', OUT,
  '-I', join(FW, 'nucleo_app', 'include'), '-I', join(FW, 'nucleo_app'),
  '-I', join(FW, 'nucleo_kbd', 'include'), '-I', join(FW, 'nucleo_ui', 'include'),
  '-I', join(FW, 'nucleo_storage', 'include'), '-I', join(FW, 'nucleo_voice', 'include'), '-I', CJSON,
  '-I', join(FW, 'nucleo_guest', 'include'), '-I', join(FW, 'nucleo_sdcontent', 'include'),
];
const COMPAT = ['-include', join(here, 'shim', 'host_compat.h')];

function compile(cc, src, obj, flags) {
  return new Promise((resolve, reject) => {
    const p = spawn(cc, [...flags, '-c', src, '-o', obj], { env });
    let err = '';
    p.stderr.on('data', (b) => { err += b; });
    p.on('close', (code) => (code === 0 ? resolve(obj) : reject(new Error(`${basename(src)}\n${err}`))));
  });
}
const stale = (src, obj) => !existsSync(obj) || statSync(obj).mtimeMs < statSync(src).mtimeMs;
async function pool(jobs, n = 8) {
  const out = []; let i = 0;
  await Promise.all(Array.from({ length: n }, async () => { while (i < jobs.length) { const j = jobs[i++]; out.push(await j()); } }));
  return out;
}

// LovyanGFX core: compiled once, cached (rebuilt only when a source is newer than its object).
const lgfxSrc = [
  join(GFX, 'lgfx', 'v1', 'LGFXBase.cpp'), join(GFX, 'lgfx', 'v1', 'LGFX_Sprite.cpp'),
  join(GFX, 'lgfx', 'v1', 'lgfx_fonts.cpp'), join(GFX, 'lgfx', 'v1', 'panel', 'Panel_Device.cpp'),
  ...readdirSync(join(GFX, 'lgfx', 'v1', 'misc')).filter((f) => f.endsWith('.cpp')).map((f) => join(GFX, 'lgfx', 'v1', 'misc', f)),
  ...readdirSync(join(GFX, 'lgfx', 'utility')).filter((f) => f.endsWith('.c')).map((f) => join(GFX, 'lgfx', 'utility', f)),
  join(here, 'host_platform.cpp'),
];
// The CJK font tables (120 MB of sources) are never drawn by NucleoOS: stub their symbols.
const fontSyms = new Set(readFileSync(join(GFX, 'lgfx', 'v1', 'lgfx_fonts.cpp'), 'utf8').match(/\blgfx_(?:efont|font_japan)_\w+/g));
const fontStub = join(LGFX_OBJ, 'font_stubs.c');
const fontStubSrc = ['#include <stdint.h>', ...[...fontSyms].map((s) => `const uint8_t ${s}[64] = {0};`), ''].join('\n');
if (!existsSync(fontStub) || readFileSync(fontStub, 'utf8') !== fontStubSrc) writeFileSync(fontStub, fontStubSrc);
lgfxSrc.push(fontStub);

const fwSrc = [
  join(FW, 'nucleo_app', 'launcher_render.cpp'), join(FW, 'nucleo_app', 'launcher_menu.cpp'),
  join(FW, 'nucleo_app', 'app_ui.cpp'), join(FW, 'nucleo_app', 'app_wifi.cpp'), join(FW, 'nucleo_ui', 'nucleo_theme.cpp'),
  join(FW, 'nucleo_ui', 'nucleo_ui_modal.cpp'),
  join(FW, 'nucleo_storage', 'nucleo_i18n.c'), join(CJSON, 'cJSON.c'),
  join(here, 'host_stubs.cpp'), join(here, 'settings_stubs.cpp'), join(here, 'scenes.cpp'),
];

const t0 = Date.now();
try {
  const lgfxObjs = await pool(lgfxSrc.map((src) => () => {
    const obj = join(LGFX_OBJ, basename(src) + '.o');
    if (!stale(src, obj)) return obj;
    const cpp = src.endsWith('.cpp');
    return compile(cpp ? GPP : GCC, src, obj, [cpp ? '-std=gnu++17' : '-std=gnu11', '-O1', '-w', '-I', join(here, 'shim'), '-I', GFX]);
  }));
  const fwObjs = await pool(fwSrc.map((src) => () => {
    const obj = join(OBJ, basename(src) + '.o');
    const cpp = src.endsWith('.cpp');
    return compile(cpp ? GPP : GCC, src, obj, [cpp ? '-std=gnu++17' : '-std=gnu11', '-O0', '-g', '-Wall', '-Wno-unused-function', ...COMPAT, ...INC]);
  }));
  execFileSync(GPP, [...fwObjs, ...lgfxObjs, '-o', join(OUT, 'ui_host.exe')], { env, stdio: 'inherit' });
} catch (e) {
  console.error('ui-host: BUILD FAILED\n' + e.message);
  process.exit(1);
}
const built = Date.now();

// ---- render ----------------------------------------------------------------------------------------------
// One process per scene (apps keep focus across opens on purpose, so scenes must not share state).
const EXE = join(OUT, 'ui_host.exe');
const sceneNames = execFileSync(EXE, ['--list'], { cwd: root, env, encoding: 'utf8' })
  .split('\n').map((l) => l.trim()).filter((l) => l && (!only || l.includes(only)));
const runLog = [];
const renderFailures = [];
// Each scene also gets a FRESH sandbox (its cwd): the relative sd/ + cfg/ mounts of shim/nucleo_board.h,
// so pins, recents, theme.json and settings.json written by one scene never reach another.
const BOXES = join(OUT, 'box');
const freeBoxes = Array.from({ length: 8 }, (_, i) => join(BOXES, `w${i}`));
await pool(sceneNames.map((name) => () => new Promise((resolve) => {
  const box = freeBoxes.pop();
  rmSync(box, { recursive: true, force: true });
  for (const d of ['sd/system/config', 'cfg/config']) mkdirSync(join(box, d), { recursive: true });
  const p = spawn(EXE, [SHOTS, name], { cwd: box, env });
  let out = '', err = '';
  p.stdout.on('data', (b) => { out += b; });
  p.stderr.on('data', (b) => { err += b; });
  p.on('close', (code) => {
    runLog.push(out);
    if (code !== 0) renderFailures.push(`${name}: exit ${code} ${err.trim()}`);
    freeBoxes.push(box);
    resolve();
  });
})), 8);
const runOut = runLog.join('');
const checks = runOut.split('\n').filter((l) => l.startsWith('ui-check:'));
for (const c of checks) console.log(c);
if (renderFailures.length) { console.error('ui-host: scenes crashed:\n  ' + renderFailures.join('\n  ')); process.exit(1); }
console.log(`ui-host: ${sceneNames.length} scenes rendered`);

// ---- PNG + hashes ---------------------------------------------------------------------------------------
const W = 240, H = 135, SCALE = 3;
function png(rgb) {                       // one scene, upscaled x3 (nearest) for legibility
  const w = W * SCALE, h = H * SCALE;
  const big = Buffer.alloc(w * h * 3);
  for (let y = 0; y < h; y++)
    for (let x = 0; x < w; x++) {
      const s = ((Math.floor(y / SCALE) * W) + Math.floor(x / SCALE)) * 3;
      rgb.copy(big, (y * w + x) * 3, s, s + 3);
    }
  return pngRaw(big, w, h);
}
function pngRaw(rgb, w, h) {
  const raw = Buffer.alloc((w * 3 + 1) * h);
  for (let y = 0; y < h; y++) {
    raw[y * (w * 3 + 1)] = 0;
    rgb.copy(raw, y * (w * 3 + 1) + 1, y * w * 3, (y + 1) * w * 3);
  }
  const chunk = (type, data) => {
    const len = Buffer.alloc(4); len.writeUInt32BE(data.length);
    const td = Buffer.concat([Buffer.from(type), data]);
    const crc = Buffer.alloc(4); crc.writeUInt32BE(zlib.crc32(td) >>> 0);
    return Buffer.concat([len, td, crc]);
  };
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(w, 0); ihdr.writeUInt32BE(h, 4); ihdr[8] = 8; ihdr[9] = 2;
  return Buffer.concat([Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]), chunk('IHDR', ihdr),
    chunk('IDAT', zlib.deflateSync(raw, { level: 9 })), chunk('IEND', Buffer.alloc(0))]);
}

const hashes = {};
const frames = {};
for (const f of readdirSync(SHOTS).filter((f) => f.endsWith('.rgb')).sort()) {
  const rgb = readFileSync(join(SHOTS, f));
  const name = f.replace(/\.rgb$/, '');
  hashes[name] = createHash('sha1').update(rgb).digest('hex').slice(0, 16);
  frames[name] = rgb;
  writeFileSync(join(SHOTS, name + '.png'), png(rgb));
  rmSync(join(SHOTS, f));
}

// One sheet per scene: every language/theme/path variant side by side (3 per row, 1:1 pixels plus a
// 2 px gutter), so a whole scene reviews in one image. build/ui-host/sheets/<surface>.<scene>.png
const SHEETS = join(OUT, 'sheets');
mkdirSync(SHEETS, { recursive: true });
for (const f of readdirSync(SHEETS)) rmSync(join(SHEETS, f));
const groups = {};
for (const n of Object.keys(frames)) { const [surface, scene] = n.split('.'); (groups[`${surface}.${scene}`] ||= []).push(n); }
const RANK = ['en.classic', 'it.classic', 'es.classic', 'fr.classic', 'de.classic', 'en.nano_banana', 'en.hacker', 'en.amoled', 'en.classic.direct'];
const rank = (n) => { const v = n.split('.').slice(2).join('.'); const i = RANK.indexOf(v); return i < 0 ? 99 : i; };
for (const m of Object.values(groups)) m.sort((a, b) => rank(a) - rank(b));
for (const [g, members] of Object.entries(groups)) {
  const cols = Math.min(3, members.length), rows = Math.ceil(members.length / cols), G = 2;
  const sw = cols * W + (cols - 1) * G, sh = rows * H + (rows - 1) * G;
  const sheet = Buffer.alloc(sw * sh * 3, 0x30);
  members.forEach((n, i) => {
    const ox = (i % cols) * (W + G), oy = Math.floor(i / cols) * (H + G);
    for (let y = 0; y < H; y++) frames[n].copy(sheet, ((oy + y) * sw + ox) * 3, y * W * 3, (y + 1) * W * 3);
  });
  writeFileSync(join(SHEETS, g + '.png'), pngRaw(sheet, sw, sh));
}
console.log(`  sheets: build/ui-host/sheets/ (order: ${groups[Object.keys(groups)[0]].map((n) => n.split('.').slice(2).join('.')).join(' | ')})`);

// Contact sheet for a quick visual review in any browser.
const names = Object.keys(hashes);
writeFileSync(join(OUT, 'index.html'), `<!doctype html><meta charset="utf-8"><title>NucleoOS native UI</title>
<style>body{background:#111;color:#ccc;font:13px system-ui;margin:16px}div{display:inline-block;margin:6px;vertical-align:top}
img{width:360px;image-rendering:pixelated;border:1px solid #333;display:block}</style>
${names.map((n) => `<div><img src="shots/${n}.png" alt="${n}"><span>${n}</span></div>`).join('\n')}`);

// ---- golden gate -----------------------------------------------------------------------------------------
const golden = existsSync(GOLDEN) ? JSON.parse(readFileSync(GOLDEN, 'utf8')) : {};
const changed = [], added = [];
for (const n of names) {
  if (!(n in golden)) added.push(n);
  else if (golden[n] !== hashes[n]) changed.push(n);
}
const missing = only ? [] : Object.keys(golden).filter((n) => !(n in hashes));
const summary = `ui-shots: ${checks.length} layout problems, ${names.length} scenes (build ${((built - t0) / 1000).toFixed(1)}s), ${changed.length} changed, ${added.length} new, ${missing.length} missing`;
if (update) {
  const next = only ? { ...golden, ...hashes } : hashes;
  writeFileSync(GOLDEN, JSON.stringify(Object.fromEntries(Object.entries(next).sort()), null, 1) + '\n');
  console.log(`${summary} -> golden updated`);
  process.exit(0);
}
for (const n of changed) console.log(`  changed  build/ui-host/shots/${n}.png`);
for (const n of added) console.log(`  new      build/ui-host/shots/${n}.png`);
for (const n of missing) console.log(`  missing  ${n}`);
console.log(summary);
console.log(`  contact sheet: build/ui-host/index.html`);
process.exit(checks.length || changed.length || missing.length || (added.length && Object.keys(golden).length) ? 1 : 0);
