// ANIMA Local — the ONE definition of what goes into the browser engine, and its fingerprint.
//
// The WASM engine (apps/anima/www/local/anima-local.{mjs,wasm}) is compiled DIRECTLY from the
// firmware sources in firmware/components/nucleo_anima — the same files, the same exclusions and
// the same online stub as the host harness (tools/anima-host/build.ps1). There is no copy to drift.
//
// What CAN drift is the built artifact: a firmware edit that is not followed by a WASM rebuild ships
// the old brain to every browser. So build.ps1 compiles engineHash() into the module (exported as
// anima_build_id) and parity.mjs — part of `npm run anima:gate` — refuses a module whose compiled-in
// id no longer matches the sources on disk. Content hash (EOL-normalised), not mtimes: a checkout or
// a copy must not look stale, and an edit must never look fresh.
//
//   node apps/anima/local/engine-src.mjs              print the source fingerprint
//   node apps/anima/local/engine-src.mjs --sources    the .c files to compile (used by build.ps1)
//   node apps/anima/local/engine-src.mjs --header F   write the build-id header (used by build.ps1)
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here  = dirname(fileURLToPath(import.meta.url));
const repo  = join(here, '..', '..', '..');
const anima = join(repo, 'firmware', 'components', 'nucleo_anima');
const host  = join(repo, 'tools', 'anima-host');

// Same exclusions as the host harness: the network tier (replaced by the host's online stub) and the
// standalone benchmark. Every OTHER firmware .c is compiled, so a new engine file can't be left out.
export const EXCLUDE = ['nucleo_anima_online.c', 'nucleo_anima_bench.c'];

const ls = (dir, ok) => (existsSync(dir) ? readdirSync(dir).filter(ok).sort().map((f) => join(dir, f)) : []);

// The translation units, in link order: firmware engine, the host's shared stubs, the wasm glue.
export function engineSources() {
  return [
    ...ls(anima, (f) => f.endsWith('.c') && !EXCLUDE.includes(f)),
    join(host, 'anima_online_stub.c'),
    join(host, 'esp_timer_host.c'),
    join(here, 'wasm_fs.c'),        // user-taught state -> the IDBFS-persisted rw/ subtree (link-time wrap)
    join(here, 'wasm_main.c'),
  ];
}

// Everything the compiled module depends on: the sources above, the headers they ACTUALLY reach
// (transitive #include closure over the build's include dirs) and the build script (flags change the
// output too). Only reachable headers count, so editing a host shim the engine never includes (the
// harness shares tools/anima-host/shim with other host tests) doesn't mark the WASM stale. A header
// name found in several include dirs counts in all of them — conservative: never a false "fresh".
const INCLUDE_DIRS = [join(here, 'shim'), join(host, 'shim'), anima, join(anima, 'include')];
const PRELUDE = join(here, 'shim', 'wasm_prelude.h');   // force-included by build.ps1 (-include)

function includeClosure(roots) {
  const seen = new Set(), out = [];
  const stack = [...roots];
  while (stack.length) {
    const f = stack.pop();
    if (seen.has(f) || !existsSync(f)) continue;
    seen.add(f); out.push(f);
    const src = readFileSync(f, 'latin1');
    for (const m of src.matchAll(/^\s*#\s*include\s*[<"]([^>"]+)[>"]/gm)) {
      const name = m[1];
      for (const d of [dirname(f), ...INCLUDE_DIRS]) {
        const p = join(d, name);
        if (existsSync(p) && !seen.has(p)) stack.push(p);
      }
    }
  }
  return out;
}

export function engineInputs() {
  const reached = includeClosure([...engineSources(), PRELUDE]);
  const sources = new Set(engineSources());
  const headers = reached.filter((f) => !sources.has(f)).sort();
  return [...engineSources(), ...headers, join(here, 'build.ps1')];
}

export function engineHash() {
  const sha = createHash('sha256');
  for (const f of engineInputs()) {
    const rel = relative(repo, f).replace(/\\/g, '/');
    const body = readFileSync(f, 'latin1').replace(/\r\n/g, '\n');   // byte-preserving, EOL-agnostic
    sha.update(rel + '\0' + body.length + '\0');
    sha.update(body, 'latin1');
  }
  return sha.digest('hex').slice(0, 32);
}

const same = (a, b) => (process.platform === 'win32' ? a.toLowerCase() === b.toLowerCase() : a === b);
const isMain = !!process.argv[1] && same(resolve(process.argv[1]), fileURLToPath(import.meta.url));
if (isMain) {
  const a = process.argv.slice(2);
  if (a[0] === '--sources') console.log(engineSources().join('\n'));
  else if (a[0] === '--header' && a[1]) {
    writeFileSync(a[1], `// generated by apps/anima/local/engine-src.mjs — do not edit\n` +
                        `#define ANIMA_LOCAL_BUILD_ID "${engineHash()}"\n`);
  } else console.log(engineHash());
}
