// SD "factory game" protection — companion to nucleo_fsprotect.h.
//
// The bundled DOS games (/data/DOS) and emulator ROMs (/data/ROMs) ship WITH the OS, but
// they live in folders the user can ALSO import into (DOS Importer, manual copy). A blanket
// "/data/DOS protect" would therefore wrongly lock the user's OWN games too. Instead, each
// bundled LEAF folder carries a hidden ".factory" manifest: a newline-separated list of the
// basenames that shipped from the factory. A file is a protected factory game iff its name
// is listed in the ".factory" of its own directory. User imports are simply absent from that
// list, so they stay freely deletable — the "vero OS" rule: system content locked, user
// content owned. (Generated by tools/gen-factory-manifests.py at build/deploy time.)
//
// Unlike nucleo_fs_is_protected() — pure string logic, called on EVERY fs op including
// listings — this DOES touch the SD, so it is meant ONLY for the rare delete/move path and
// for the listing lock-flag, NEVER the read hot path. The ".factory" file itself is pinned
// here too, so the lock can't be lifted by deleting the manifest.
//
// RAM: the manifest is read STREAMING, one line into a small stack buffer — never slurped.
// A folder can hold hundreds of ROMs (a 9 KB+ list); slurping that would threaten this
// PSRAM-less, ~18 KB-heap board. Zero heap here.
//
// Scope-gated to /data/DOS and /data/ROMs so a stray ".factory" elsewhere can never pin a
// user's own folder.
#pragma once
#include <stdio.h>
#include <string.h>
#include <strings.h>
#include <stdbool.h>
#include "nucleo_fsprotect.h"   // nucleo_fs__norm / __seg / __base, NUCLEO_SD_MOUNT

// Does one raw ".factory" line name `base` (a bare filename)? Trims leading/trailing blanks
// and a trailing CR/LF, skips blank and '#' comment lines, compares case-insensitively
// (FATFS is). Pure and allocation-free — host-testable; the single source of match logic.
static inline bool nucleo_fs_factory_line_eq(const char *line, const char *base)
{
    if (!line || !base || !*base) return false;
    const char *s = line;
    while (*s == ' ' || *s == '\t') s++;
    if (*s == '#' || *s == '\0' || *s == '\n' || *s == '\r') return false;   // comment/blank
    const char *e = s + strlen(s);
    while (e > s && (e[-1] == '\n' || e[-1] == '\r' || e[-1] == ' ' || e[-1] == '\t')) e--;
    size_t blen = strlen(base);
    return (size_t)(e - s) == blen && strncasecmp(s, base, blen) == 0;
}

// Is `base` listed in "<dir_abs>/.factory"? Streams the file (no heap). False if no manifest.
static inline bool nucleo_fs_factory_file_has(const char *dir_abs, const char *base)
{
    char path[300];
    snprintf(path, sizeof path, "%s/.factory", dir_abs);
    FILE *f = fopen(path, "r");
    if (!f) return false;
    char line[160];                          // longest ROM basenames are ~80 chars; 160 is slack
    bool hit = false;
    while (fgets(line, sizeof line, f)) {
        if (nucleo_fs_factory_line_eq(line, base)) { hit = true; break; }
    }
    fclose(f);
    return hit;
}

// Is the folder `dir_abs` a bundled-game leaf (i.e. could it carry a ".factory")? Used to gate
// the listing's manifest read to the in-scope trees only.
static inline bool nucleo_fs_factory_scope(const char *dir_abs)
{
    char rel[256];
    nucleo_fs__norm(dir_abs, rel, sizeof rel);
    return nucleo_fs__seg(rel, "data/DOS") || nucleo_fs__seg(rel, "data/ROMs");
}

// True when `abs` (an "/sd"-rooted path) is a bundled factory game OR the ".factory" manifest
// itself, under /data/DOS or /data/ROMs. Streams one small file — use only on delete/move.
static inline bool nucleo_fs_is_factory(const char *abs)
{
    if (!abs || !*abs) return false;

    char rel[256];
    nucleo_fs__norm(abs, rel, sizeof rel);
    if (!nucleo_fs__seg(rel, "data/DOS") && !nucleo_fs__seg(rel, "data/ROMs")) return false;

    const char *base = nucleo_fs__base(rel);
    if (strcasecmp(base, ".factory") == 0) return true;     // pin the manifest itself

    const char *slash = strrchr(rel, '/');
    if (!slash || slash == rel) return false;               // no parent dir → not a game file

    char dir[300];
    snprintf(dir, sizeof dir, "%s%.*s", NUCLEO_SD_MOUNT, (int)(slash - rel), rel);
    return nucleo_fs_factory_file_has(dir, base);
}
