// Verify npx.js decodes a real binary .npx (generated by tools/npx_gen).
// Run: node apps/dj/test/_test_npx.mjs   (after python tools/npx_gen/_gen_sample.py)
import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { parseNpx } from '../www/npx.js';

const here = dirname(fileURLToPath(import.meta.url));
const sample = resolve(here, '../../../tools/npx_gen/_sample.npx');

if (!existsSync(sample)) {
  console.log('SKIP: fixture mancante — genera con: python tools/npx_gen/_gen_sample.py');
  process.exit(0);
}

let pass = 0, fail = 0;
const ok = (n, c, e = '') => c ? (pass++, console.log('  ok  ', n))
                               : (fail++, console.log('  FAIL', n, e));

const buf = readFileSync(sample);
const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
const t = parseNpx(ab);

console.log(`bpm=${t.bpm} kicks=${t.kicks.length} drop=${t.drop_sec}s ` +
            `camelot=${t.camelot} bands.bass=${t.bands.bass.toFixed(2)} ` +
            `beat.conf=${t.beat.conf.toFixed(2)} intro=${t.intro_sec} outro=${t.outro_sec}`);

ok('bpm ~150', Math.abs(t.bpm - 150) < 3, '' + t.bpm);
ok('found ~49 kicks', Math.abs(t.kicks.length - 49) <= 2, '' + t.kicks.length);
ok('kick times sub-frame (not on 0.1 grid)',
   t.kicks.some((k) => Math.abs(k * 10 - Math.round(k * 10)) > 0.05), '');
ok('drop ~13s', t.drop_sec > 11 && t.drop_sec < 15, '' + t.drop_sec);
ok('beat grid period ~0.4s', Math.abs(t.beat.period_s - 0.4) < 0.02, '' + t.beat.period_s);
ok('beat confidence high', t.beat.conf > 0.5, '' + t.beat.conf);
ok('camelot present', !!t.camelot, '' + t.camelot);
ok('phrase16 derived', t.bars.phrase16_period_s > 0, '' + t.bars.phrase16_period_s);

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
