#!/usr/bin/env node
// Host gate for the native launcher model (npm run launcher:test).
//
// 1. Counts every nucleo_app_register() call site in the firmware — an upper bound on what any board
//    registers — and extracts the real app table (id, name, category) from the app definitions.
// 2. Compiles the REAL firmware/components/nucleo_app/launcher_menu.cpp against a few stubs and runs
//    launcher-ctest.cpp: capacity (the v0.4.0 bug: 65-68 apps into 64 slots, silently dropped),
//    tree integrity, navigation, Spotlight filter, pin-to-Home persistence, Solo return-cursor.
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync, existsSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readRegistry } from './apps.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..');
const fw = join(root, 'firmware', 'components');
const out = join(root, 'build', 'launcher-host');

const { apps: list, callSites, unreached } = readRegistry();
if (unreached.length) console.log(`note: app defs never registered at boot: ${unreached.join(', ')}`);
const apps = new Map(list.map((a) => [a.id, a]));
const perBoard = { original: list.filter((a) => !a.advOnly).length, adv: list.length };
const cats = new Set([...apps.values()].filter((a) => a.id !== 'anima').map((a) => a.cat));
const maxCats = Number(/#define MAX_CATS (\d+)/.exec(readFileSync(join(fw, 'nucleo_app', 'launcher_menu.cpp'), 'utf8'))[1]);
if (cats.size > maxCats) {
  console.error(`launcher-model: ${cats.size} categories (${[...cats].join(', ')}) > MAX_CATS ${maxCats}`);
  process.exit(1);
}

rmSync(out, { recursive: true, force: true });
mkdirSync(join(out, 'cfg', 'config'), { recursive: true });
const q = (s) => JSON.stringify(s);
writeFileSync(join(out, 'apps.gen.h'), [
  '// Generated by tools/launcher-host/check.mjs from the firmware app definitions. Do not edit.',
  '#pragma once',
  'struct RealApp { const char *id, *name, *cat; };',
  `static const RealApp REAL_APPS[] = {`,
  ...[...apps.values()].map((a) => `    { ${q(a.id)}, ${q(a.name)}, ${q(a.cat)} },`),
  '};',
  `static const int REAL_APP_N = ${apps.size};`,
  `static const int REAL_CALL_SITES = ${callSites};`,
  `static const int REAL_ORIGINAL_N = ${perBoard.original};`,
  `static const int REAL_ADV_N = ${perBoard.adv};`,
  '',
].join('\n'));

const GPP = ['C:/msys64/mingw64/bin/g++.exe', 'g++'].find((p) => p === 'g++' || existsSync(p));
const env = { ...process.env, PATH: `C:/msys64/mingw64/bin;${process.env.PATH}` };
const exe = join(out, 'launcher_test.exe');
try {
  execFileSync(GPP, [
    '-std=gnu++17', '-O1', '-Wall', '-Wextra', '-Werror',
    '-I', join(here, 'stubs'), '-I', out,
    '-I', join(fw, 'nucleo_app', 'include'), '-I', join(fw, 'nucleo_app'),
    '-I', join(fw, 'nucleo_kbd', 'include'), '-I', join(fw, 'nucleo_ui', 'include'),
    join(fw, 'nucleo_app', 'launcher_menu.cpp'), join(here, 'launcher-ctest.cpp'),
    '-o', exe,
  ], { cwd: root, env, stdio: 'inherit' });
} catch {
  console.error('launcher-model: COMPILE FAILED');
  process.exit(1);
}
try {
  execFileSync(exe, [], { cwd: root, env, stdio: 'inherit' });
} catch {
  process.exit(1);
}
