#!/usr/bin/env python3
"""Vendor the official Bosch BMI270 config blob into a C header for the nucleo_imu component.

The BMI270 needs an ~8 KB configuration array uploaded at init before it streams data (the well-known
BMI270 quirk). Those bytes are Bosch's (BSD-3-Clause) and are NOT reproduced by hand anywhere in this
repo. This script fetches the official bmi270.c, extracts `bmi270_config_file[]`, and writes
firmware/components/nucleo_imu/bmi270_config.h. Run it once; commit the generated header (or re-run
on a fresh checkout). Without the header, nucleo_imu compiles fine and just reports the IMU absent.

Usage:
    python tools/gen-bmi270-config.py
"""
import os
import re
import sys
import urllib.request

URL = "https://raw.githubusercontent.com/boschsensortec/BMI270_SensorAPI/master/bmi270.c"
OUT = os.path.join(os.path.dirname(__file__), "..", "firmware", "components", "nucleo_imu", "bmi270_config.h")


def main():
    print("Fetching", URL)
    try:
        src = urllib.request.urlopen(URL, timeout=30).read().decode("utf-8", "replace")
    except Exception as e:  # noqa: BLE001 - report any network/HTTP failure plainly
        print("ERROR: download failed:", e, file=sys.stderr)
        return 2

    m = re.search(r"bmi270_config_file\s*\[\s*\]\s*=\s*\{(.*?)\}\s*;", src, re.S)
    if not m:
        print("ERROR: bmi270_config_file[] not found in the fetched source", file=sys.stderr)
        return 2

    data = [int(x, 16) for x in re.findall(r"0x[0-9a-fA-F]{1,2}", m.group(1))]
    n = len(data)
    if n < 4096:
        print("ERROR: only %d bytes parsed (expected ~8192) — aborting" % n, file=sys.stderr)
        return 2
    if n > 8192:
        # The driver's 12-bit word address (INIT_ADDR) tops out at 8192 bytes; refuse a larger blob.
        print("ERROR: blob is %d bytes (>8192); driver word-addressing can't load it" % n, file=sys.stderr)
        return 2

    out = os.path.normpath(OUT)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", newline="\n", encoding="ascii") as f:
        f.write("// AUTO-GENERATED by tools/gen-bmi270-config.py - official Bosch BMI270 config blob.\n")
        f.write("// (c) Bosch Sensortec GmbH, BSD-3-Clause. Do not edit by hand. See nucleo_imu.c.\n")
        f.write("#pragma once\n#include <stdint.h>\n#include <stddef.h>\n\n")
        f.write("static const uint8_t BMI270_CONFIG_FILE[] = {\n")
        for i in range(0, n, 12):
            f.write("    " + ", ".join("0x%02x" % b for b in data[i:i + 12]) + ",\n")
        f.write("};\n")
        f.write("#define BMI270_CONFIG_FILE_LEN ((size_t)sizeof(BMI270_CONFIG_FILE))\n")

    print("Wrote %s (%d bytes)" % (out, n))
    return 0


if __name__ == "__main__":
    sys.exit(main())
