#!/usr/bin/env python3
"""Generate the hidden ".factory" manifests that pin BUNDLED games against deletion.

NucleoOS ships DOS games (deploy/sd/data/DOS) and emulator ROMs (deploy/sd/data/ROMs/*)
in folders the user can also import into. The firmware must tell factory games (locked)
apart from user imports (deletable). It does so by reading a ".factory" file in each leaf
folder: a newline list of the basenames that shipped from the factory. A file is pinned
iff its name is listed there — user imports are simply absent, so they stay deletable.

This script (re)writes those ".factory" files from whatever game payload currently sits in
the repo's deploy/sd image. Run it whenever you add/remove a bundled game, then deploy.

    python tools/gen-factory-manifests.py            # write manifests
    python tools/gen-factory-manifests.py --check    # CI: fail if out of date (no writes)

Matches the firmware reader in firmware/components/nucleo_board/include/nucleo_fsfactory.h.
"""
import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Source of truth for the factory set = the full provisioning image.
SRC = os.path.join(ROOT, "deploy", "sd", "data")
# Where manifests are written. sd-safe carries them too so `sd-sync` can push the lock to a
# device that was provisioned earlier (its games are already there; only the .factory is new).
TARGETS_DATA = [
    os.path.join(ROOT, "deploy", "sd", "data"),
    os.path.join(ROOT, "deploy", "sd-safe", "data"),
]

# Leaf folders that hold bundled game payload, with the extensions that count as "a game".
# Aux files (library.json, README, the .factory itself) are intentionally NOT listed, so the
# DOS Importer can keep rewriting library.json and the user can tidy READMEs.
TARGETS = [
    ("DOS",      {".jsdos", ".com", ".exe", ".bat", ".zip"}),
    ("ROMs/gb",  {".gb"}),
    ("ROMs/gbc", {".gbc"}),
    ("ROMs/gg",  {".gg"}),
    ("ROMs/nes", {".nes"}),
    ("ROMs/sms", {".sms"}),
]

MANIFEST = ".factory"
HEADER = "# Bundled factory games -- pinned against deletion. Generated by tools/gen-factory-manifests.py. Do not edit.\n"


def wanted(folder, exts):
    """Sorted basenames of bundled game files in `folder` (abs path)."""
    if not os.path.isdir(folder):
        return None
    names = []
    for name in os.listdir(folder):
        if name == MANIFEST:
            continue
        if not os.path.isfile(os.path.join(folder, name)):
            continue
        if os.path.splitext(name)[1].lower() in exts:
            names.append(name)
    return sorted(names, key=str.lower)


def render(names):
    return HEADER + "".join(n + "\n" for n in names)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if any manifest is stale; write nothing")
    args = ap.parse_args()

    stale, written = [], []
    for rel, exts in TARGETS:
        names = wanted(os.path.join(SRC, *rel.split("/")), exts)
        if not names:
            continue  # folder not shipped, or holds no bundled games — nothing to pin
        desired = render(names)
        for base in TARGETS_DATA:
            folder = os.path.join(base, *rel.split("/"))
            path = os.path.join(folder, MANIFEST)
            current = None
            if os.path.exists(path):
                with open(path, "r", encoding="utf-8", newline="") as f:
                    current = f.read()
            if current == desired:
                continue
            label = os.path.relpath(path, ROOT)
            if args.check:
                stale.append(label)
                continue
            os.makedirs(folder, exist_ok=True)
            with open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(desired)
            written.append((label, len(names)))

    if args.check:
        if stale:
            print("STALE factory manifests (run tools/gen-factory-manifests.py):", ", ".join(stale))
            return 1
        print("factory manifests up to date")
        return 0

    for label, n in written:
        print(f"  wrote {label}  ({n} games)")
    if not written:
        print("  (all manifests already current)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
